-- Krafft — Phase 17: exercise library expansion + hypertrophy guidance.
-- Run this once in the Supabase SQL Editor against the existing live
-- database. Fresh installs get it automatically from reset-schema.sql
-- instead.
--
-- Adds four hypertrophy-guidance columns to the existing `exercises`
-- table (rep range, rest interval, tempo note, one-line mind-muscle-
-- connection cue — all static/pre-written, not AI-generated), then
-- replaces the ~32-exercise seed from phase13 with the full ~75-exercise
-- library requested. Safe to truncate-and-reinsert: nothing references
-- exercises.id by foreign key (lifts references an exercise by its name,
-- a plain text column), so there's no dependent data to preserve here.
--
-- Citation copy for the rep-range guidance lives in CITATION_LIBRARY in
-- index.html (static JS, same pattern as the Layer 1 tips library), not a
-- database column — it's the same citation reused across every exercise's
-- hypertrophy section, not a per-exercise value, so a column here would
-- just duplicate the same string ~75 times for no benefit. The
-- rest-interval and tempo fields below are shown as general coaching
-- guidance with no citation attached — the source originally cited for
-- rest interval (Grgic et al., 2018) covers strength outcomes, not
-- hypertrophy, so it was removed rather than misapplied. A separate
-- training-frequency citation isn't per-exercise at all — it's surfaced
-- once, next to the training split card, where frequency actually gets
-- decided.

alter table exercises add column if not exists hypertrophy_rep_range text;
alter table exercises add column if not exists hypertrophy_rest_interval text;
alter table exercises add column if not exists hypertrophy_tempo text;
alter table exercises add column if not exists hypertrophy_mind_muscle_cue text;

truncate table exercises;

insert into exercises (name, muscle_group, body_region, secondary_regions, equipment, cue_setup, cue_execution, cue_mistake, cue_bracing, hypertrophy_rep_range, hypertrophy_rest_interval, hypertrophy_tempo, hypertrophy_mind_muscle_cue) values

-- ── Chest ──────────────────────────────────────────────────────────────
('Bench Press', 'Push', 'chest', '{triceps,shoulders}', 'Barbell',
  'Set up with eyes under the bar, feet flat and driving into the floor, shoulder blades pulled back and down.',
  'Lower the bar to your lower chest under control, then press up and slightly back toward your face.',
  'Flaring the elbows straight out to the sides instead of tucking them ~45° — it stresses the shoulder more and gives you less pressing power.',
  'Take a breath into your belly before unracking, and hold it through the hardest part of each rep.',
  '6–12 reps', '2–3 min', '2-1-1 tempo — lower for 2 seconds, brief pause on the chest, drive up',
  'Think about pushing yourself away from the bar, not just pushing the bar away from you.'),
('Incline Bench Press', 'Push', 'chest', '{shoulders,triceps}', 'Barbell',
  'Set the bench to a 30–45° incline — steeper shifts the work to shoulders, flatter shifts it back to chest.',
  'Lower the bar to your upper chest, just below the collarbone, then press up and slightly back.',
  'Setting the incline too steep turns this into an overhead press with extra shoulder strain instead of an upper-chest exercise.',
  'Keep your feet planted and glutes on the bench — don''t let your lower back arch off the pad to chase more range.',
  '8–12 reps', '2 min', '2-1-1 tempo',
  'Focus on driving through your upper chest, not just your shoulders.'),
('Decline Bench Press', 'Push', 'chest', '{triceps}', 'Barbell',
  'Secure your feet in the decline bench''s foot pads, lie back with eyes under the bar.',
  'Lower the bar to your lower chest, then press up and slightly back.',
  'Bouncing the bar off the chest to use momentum instead of controlling the full range.',
  'Keep your shoulder blades pulled back and down against the bench throughout.',
  '8–12 reps', '2 min', '2-1-1 tempo',
  'Focus on squeezing the lower chest at the top of the press.'),
('Dumbbell Bench Press', 'Push', 'chest', '{triceps,shoulders}', 'Dumbbell',
  'Lie on a flat bench with a dumbbell in each hand at chest level, elbows bent.',
  'Press the dumbbells up until your arms are extended, then lower under control back to chest level.',
  'Letting the dumbbells drift too far apart or together at the top, losing tension on the chest.',
  'Keep your feet flat on the floor and glutes on the bench for a stable base to press from.',
  '8–12 reps', '90 sec–2 min', '2-1-2 tempo',
  'Squeeze your chest together at the top like you''re hugging a barrel.'),
('Incline Dumbbell Press', 'Push', 'chest', '{shoulders,triceps}', 'Dumbbell',
  'Set the bench to a 30–45° incline, dumbbells at shoulder height.',
  'Press the dumbbells up and slightly in, then lower under control.',
  'Setting the incline too steep, which shifts the work to the shoulders instead of the upper chest.',
  'Keep your lower back flat against the bench, not arched off it.',
  '8–12 reps', '90 sec', '2-1-2 tempo',
  'Picture pressing up and slightly toward the ceiling above your opposite eye.'),
('Dumbbell Fly', 'Push', 'chest', '{shoulders}', 'Dumbbell',
  'Lie on a flat bench with dumbbells held above your chest, a slight bend in the elbows.',
  'Lower the dumbbells out to the sides in a wide arc until you feel a stretch in the chest, then bring them back together.',
  'Bending the elbows more as the weight gets heavy, which turns the fly into a press.',
  'Keep that slight elbow bend fixed throughout — don''t let it change between reps.',
  '10–15 reps', '60–90 sec', '3-1-1 tempo — slow, controlled stretch down',
  'Imagine wrapping your arms around a large barrel, feeling the stretch across your chest.'),
('Cable Fly', 'Push', 'chest', '{shoulders}', 'Cable',
  'Set both pulleys to chest height (or adjust for upper/lower chest emphasis), grip the handles with a slight forward lean.',
  'Bring your hands together in front of your chest in a hugging motion, then return under control.',
  'Using too much weight and turning the movement into a press by bending the elbows more.',
  'Keep a stable, slight forward lean and don''t let your torso rock to help move the weight.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Focus on squeezing your chest together at the peak, holding briefly before releasing.'),
('Pec Deck', 'Push', 'chest', '{shoulders}', 'Machine',
  'Sit with your back flat against the pad, forearms or hands on the arm pads at chest height.',
  'Bring the pads together in front of your chest, then let them return under control.',
  'Letting the weight stack slam down between reps instead of controlling the stretch.',
  'Keep your back pressed into the pad throughout — don''t let it round forward as you squeeze.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Squeeze and hold for a full second at the point your hands are closest together.'),
('Push-Up', 'Push', 'chest', '{triceps,abs}', 'Bodyweight',
  'Hands slightly wider than shoulders, body in a straight line from head to heels.',
  'Lower your chest to just above the floor with elbows at roughly 45°, then press back up.',
  'Letting the hips sag or pike up breaks the straight-line position and shifts load away from the chest.',
  'Brace your abs and squeeze your glutes throughout — treat it like a moving plank, not just an arm exercise.',
  '10–20 reps (add weight or elevate feet once bodyweight gets easy)', '60–90 sec', '2-1-1 tempo',
  'Think about pushing the floor away from you rather than just straightening your arms.'),
('Dip (Chest-Focused)', 'Push', 'chest', '{triceps,shoulders}', 'Bodyweight',
  'Grip the bars with arms straight, lean your torso forward to bias the chest over the triceps.',
  'Lower until you feel a stretch in the chest, then press back up, keeping the forward lean.',
  'Staying too upright, which shifts the emphasis to triceps instead of chest.',
  'Keep your core braced and shoulders down — a forward lean should come from the hips, not a rounded back.',
  '8–15 reps (add weight once bodyweight gets easy)', '90 sec–2 min', '2-1-1 tempo',
  'Lead with your chest on the way down, like you''re diving forward into the stretch.'),

-- ── Back ───────────────────────────────────────────────────────────────
('Deadlift', 'Pull', 'back', '{hamstrings,glutes}', 'Barbell',
  'Bar over mid-foot, shins close to the bar, grip just outside your knees, hips higher than the knees, chest up.',
  'Drive through the floor with your legs while keeping the bar close to your body until you''re standing tall.',
  'Letting the bar drift away from your shins/thighs turns the lift into a lower-back grinder instead of a leg-and-hip drive.',
  'Take a big breath and brace your entire torso like a weightlifting belt before the bar leaves the floor.',
  '5–10 reps', '2–3 min', 'controlled down (2-3 sec), no bounce off the floor on the next rep',
  'Think about pushing the floor away with your legs first, then finishing tall with your hips.'),
('Romanian Deadlift', 'Legs', 'hamstrings', '{glutes,back}', 'Barbell',
  'Start standing with the bar at hip height, soft bend in the knees that stays fixed through the rep.',
  'Push your hips back, lowering the bar along your legs until you feel a stretch in your hamstrings, then drive your hips forward to stand.',
  'Bending the knees more as the bar lowers turns it into a squat and takes tension off the hamstrings — the actual target.',
  'Keep your back flat and core braced — the movement is a hip hinge, not a spinal round.',
  '8–12 reps', '90 sec–2 min', '3-1-1 tempo — slow lowering to really feel the stretch',
  'Focus on feeling a deep stretch in your hamstrings before you reverse the movement.'),
('Barbell Row', 'Pull', 'back', '{biceps,forearms}', 'Barbell',
  'Hinge at the hips to roughly a 45° torso angle, grip just outside shoulder width.',
  'Pull the bar to your lower ribcage, squeezing your shoulder blades together at the top.',
  'Standing up more with each rep (turning it into a mini deadlift) as fatigue sets in instead of holding the hinge.',
  'Keep your core braced and back flat throughout — this is a hip-hinge position, not just an arm pull.',
  '8–12 reps', '90 sec–2 min', '1-1-2 tempo — control the lowering more than the pull',
  'Pull with your elbows, not your hands — imagine driving your elbows toward the ceiling.'),
('Pendlay Row', 'Pull', 'back', '{biceps,forearms}', 'Barbell',
  'Bar on the floor, hinge over to a flat-back, near-horizontal torso position, grip just outside shoulder width.',
  'Pull the bar explosively off the floor to your lower chest/upper abs, then lower it back to a dead stop each rep.',
  'Using body English (a hip heave) to start the pull instead of pulling with the back.',
  'Keep your torso locked in that horizontal position throughout the set — it shouldn''t rise as you fatigue.',
  '6–10 reps', '90 sec–2 min', 'explosive up, controlled down, dead stop each rep',
  'Reset your brace fully between every rep — treat each one as its own lift.'),
('Dumbbell Row', 'Pull', 'back', '{biceps,forearms}', 'Dumbbell',
  'One knee and hand on a bench for support, other foot on the floor, dumbbell hanging in your free hand.',
  'Pull the dumbbell up to your hip, driving your elbow back, then lower under control.',
  'Rotating your torso to help heave the weight up instead of keeping it square.',
  'Keep your supporting arm locked and your back flat, not rounded, throughout the set.',
  '8–12 reps', '90 sec', '1-1-2 tempo',
  'Imagine trying to touch your elbow to the ceiling at the top of each rep.'),
('T-Bar Row', 'Pull', 'back', '{biceps,forearms}', 'Barbell',
  'Straddle the bar with a chest pad or hinge over it, grip the handles with a neutral or wide grip.',
  'Pull the weight up to your torso, squeezing your shoulder blades together, then lower under control.',
  'Using a short, jerky range of motion instead of a full stretch-to-squeeze pull.',
  'Keep your chest against the pad (if using one) or your hinge position fixed throughout.',
  '8–12 reps', '90 sec–2 min', '1-1-2 tempo',
  'Focus on pulling your shoulder blades together, not just bending your elbows.'),
('Seated Cable Row', 'Pull', 'back', '{biceps,forearms}', 'Cable',
  'Sit with knees slightly bent, back tall, grip the handle with arms extended.',
  'Pull the handle to your torso, squeezing your shoulder blades together, then extend back out under control.',
  'Rounding your lower back to add a few extra inches of pull range instead of keeping a tall, stable torso.',
  'Keep your torso upright and braced throughout — the movement should come from your arms and shoulder blades, not your spine rocking.',
  '10–12 reps', '90 sec', '1-1-2 tempo',
  'Lead the pull with your chest moving toward the handle, not just your arms bending.'),
('Lat Pulldown', 'Pull', 'back', '{biceps}', 'Cable',
  'Grip slightly wider than shoulder width, sit tall with thighs secured under the pad.',
  'Pull the bar to your upper chest, driving your elbows down and back, then control it back up.',
  'Leaning back excessively and using body weight instead of your back muscles to move the bar.',
  'Keep your chest up and core braced — a small, controlled lean is fine, but a big swing is momentum, not strength.',
  '10–12 reps', '90 sec', '1-1-2 tempo',
  'Think about pulling your elbows down toward your back pockets.'),
('Pull-Up', 'Pull', 'back', '{biceps,forearms}', 'Bodyweight',
  'Grip just outside shoulder width, palms facing away, hang with arms fully extended.',
  'Pull your chin over the bar leading with your chest, then lower back to a full hang under control.',
  'Only doing the top half of the rep (partial range) trains less muscle and builds strength you can''t actually use.',
  'Keep a slight hollow-body brace so you''re not using an uncontrolled kip or swing to gain momentum.',
  '6–12 reps (add weight once bodyweight gets easy)', '90 sec–2 min', '1-1-2 tempo',
  'Drive your elbows down and back rather than just pulling with your hands.'),
('Chin-Up', 'Pull', 'back', '{biceps}', 'Bodyweight',
  'Grip shoulder width, palms facing you, hang with arms fully extended.',
  'Pull yourself up until your chin clears the bar, then lower back down under control.',
  'Turning it into a chest-up crunch instead of a straight vertical pull reduces the actual back/bicep work.',
  'Keep your ribs down and core tight to avoid an excessive arch through your lower back.',
  '6–12 reps', '90 sec–2 min', '1-1-2 tempo',
  'Feel your lats stretch fully at the bottom before initiating the next pull.'),
('Straight-Arm Pulldown', 'Pull', 'back', '{abs}', 'Cable',
  'Stand facing a high cable pulley, grip a straight bar or rope with arms extended overhead.',
  'Keeping your arms mostly straight, pull the bar down in an arc to your thighs, then let it return.',
  'Bending the elbows significantly, which turns this into a tricep pushdown instead of a lat isolation move.',
  'Keep a slight forward hinge at the hips and brace your core so the movement comes from the shoulder, not the back.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Imagine pulling an imaginary bar down and back toward your hips in a wide arc.'),
('Face Pull', 'Pull', 'shoulders', '{back}', 'Cable',
  'Set the cable at roughly face height, grip the rope with palms facing in.',
  'Pull the rope toward your face, flaring your elbows out wide and rotating your hands back.',
  'Pulling with too much weight and turning it into a row instead of a high-elbow rear-delt/rotator cuff movement.',
  'Keep your upper back tight and shoulders down away from your ears throughout the pull.',
  '12–20 reps', '60 sec', '2-1-2 tempo',
  'Aim the rope toward your forehead and really flare your elbows wide at the end.'),

-- ── Shoulders ──────────────────────────────────────────────────────────
('Overhead Press', 'Push', 'shoulders', '{triceps,abs}', 'Barbell',
  'Grip just outside shoulder width, bar resting on your front delts, elbows slightly in front of the bar.',
  'Press straight up, moving your head back slightly to let the bar pass, then push your head through at the top.',
  'Leaning back excessively to help the bar clear your face turns this into an incline press and stresses the lower back.',
  'Squeeze your glutes and brace your abs like you''re about to be punched in the stomach — a loose torso leaks power.',
  '6–10 reps', '2 min', 'controlled 2 sec down, drive up with intent',
  'Push your head through at the top like you''re trying to look through a window above you.'),
('Seated Dumbbell Press', 'Push', 'shoulders', '{triceps}', 'Dumbbell',
  'Sit on a bench with back support, dumbbells at shoulder height, palms facing forward.',
  'Press the dumbbells up until arms are extended, then lower under control.',
  'Arching the lower back excessively to help push the weight overhead.',
  'Keep your back flat against the bench pad and core braced throughout.',
  '8–12 reps', '90 sec–2 min', '2-1-2 tempo',
  'Press the dumbbells up and slightly together, imagining you''re pressing through a narrow tube.'),
('Arnold Press', 'Push', 'shoulders', '{triceps}', 'Dumbbell',
  'Sit with dumbbells in front of your shoulders, palms facing you.',
  'As you press up, rotate your palms to face forward, finishing with arms extended overhead; reverse the rotation on the way down.',
  'Rushing the rotation instead of timing it smoothly with the press.',
  'Keep your core tight so the rotation doesn''t pull you off balance.',
  '8–12 reps', '90 sec', '2-1-2 tempo',
  'Feel the rotation take your front delt through a longer range than a standard press.'),
('Lateral Raise', 'Push', 'shoulders', '{}', 'Dumbbell',
  'Stand with a slight forward lean, dumbbells at your sides with a soft bend in the elbows.',
  'Raise the dumbbells out to the sides until roughly shoulder height, leading with your elbows.',
  'Using momentum to swing the weight up trains your traps more than your side delts — the target muscle.',
  'Keep your core braced so you''re not using a body swing to substitute for shoulder strength.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Lead with your elbows, not your hands, like you''re pouring water out of a jug at the top.'),
('Front Raise', 'Push', 'shoulders', '{}', 'Dumbbell',
  'Stand holding dumbbells at your thighs, palms facing your body or each other.',
  'Raise one or both dumbbells straight in front of you to shoulder height, then lower under control.',
  'Swinging the weight up using momentum from the hips and lower back.',
  'Keep your core braced and avoid leaning back to help lift the weight.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Focus on lifting with your front delt, not swinging from your torso.'),
('Rear Delt Fly', 'Pull', 'shoulders', '{back}', 'Dumbbell',
  'Hinge forward at the hips, dumbbells hanging below your shoulders, slight bend in the elbows.',
  'Raise the dumbbells out to the sides, squeezing your shoulder blades together, then lower under control.',
  'Standing too upright, which shifts the work to the upper traps instead of the rear delts.',
  'Keep your hinge position fixed and your core braced so you''re not using body momentum.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Imagine pulling your shoulder blades toward each other, not just raising your arms.'),
('Cable Lateral Raise', 'Push', 'shoulders', '{}', 'Cable',
  'Stand side-on to a low cable pulley, grip the handle across your body.',
  'Raise your arm out to the side to shoulder height, then lower under control.',
  'Using body lean to help swing the weight up instead of isolating the shoulder.',
  'Keep your torso upright and stable — the cable''s constant tension means less momentum is available to cheat with.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Feel constant tension through the whole range, especially at the bottom where dumbbells usually lose it.'),
('Upright Row', 'Pull', 'shoulders', '{back}', 'Barbell',
  'Stand holding a bar or dumbbells in front of your thighs, hands shoulder width or slightly closer.',
  'Pull the weight straight up along your body to roughly chest height, leading with your elbows, then lower under control.',
  'Pulling the bar too high or with a very narrow grip, which can aggravate the shoulder joint for some lifters.',
  'Keep your core braced and avoid using a big body heave to start the pull.',
  '10–15 reps', '60–90 sec', '2-1-2 tempo',
  'Think about leading the pull with your elbows staying above your hands throughout.'),
('Shrug', 'Pull', 'back', '{forearms}', 'Barbell',
  'Stand holding a bar or dumbbells at your sides, arms straight.',
  'Elevate your shoulders straight up toward your ears, pause briefly, then lower under control.',
  'Rolling the shoulders in a circular motion instead of a straight up-and-down path.',
  'Keep your arms straight and core braced — the movement should come entirely from the shoulders.',
  '10–15 reps', '60–90 sec', '1-1-2 tempo — pause at the top',
  'Try to touch your shoulders to your ears, holding the squeeze for a full second.'),

-- ── Legs: Quads/Glutes ─────────────────────────────────────────────────
('Back Squat', 'Legs', 'quads', '{glutes,hamstrings}', 'Barbell',
  'Bar on your upper traps (high bar) or rear delts (low bar), feet roughly shoulder width.',
  'Break at the hips and knees together, descending until your hip crease is at or below knee level, then drive back up.',
  'Letting the knees cave inward on the way up, especially on a heavy last rep — it''s a common sign of fatigue or weak hips.',
  'Take a big breath and brace your abs hard before descending — hold that brace through the bottom of the rep.',
  '6–12 reps', '2–3 min', 'controlled 2-3 sec down, drive up with intent',
  'Think about spreading the floor apart with your feet as you stand up.'),
('Front Squat', 'Legs', 'quads', '{abs,glutes}', 'Barbell',
  'Bar racked across your front delts with elbows high, grip can be clean-style or crossed-arm.',
  'Squat down keeping your torso more upright than a back squat, then drive up through your heels/mid-foot.',
  'Letting the elbows drop lowers the bar off your shoulders and pitches your torso forward, losing the position.',
  'Brace your abs hard — an upright torso here depends more on core strength than on the back squat.',
  '6–10 reps', '2–3 min', 'controlled down, no bounce at the bottom',
  'Keep your elbows up and chest tall — imagine balancing a cup of water on your chest.'),
('Goblet Squat', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Hold a dumbbell or kettlebell vertically against your chest, feet shoulder width.',
  'Squat down between your knees until your thighs are at least parallel, then drive back up.',
  'Letting the weight pull your torso forward and rounding your upper back.',
  'Keep the weight held tight against your chest and your torso upright throughout.',
  '10–15 reps', '90 sec', '2-1-2 tempo',
  'Use your elbows to gently push your knees out as you descend.'),
('Leg Press', 'Legs', 'quads', '{glutes,hamstrings}', 'Machine',
  'Feet shoulder width on the platform, lower back flat against the pad.',
  'Lower the platform until your knees reach roughly 90°, then press back up without locking your knees hard at the top.',
  'Letting your lower back round off the pad as the weight gets heavy — usually a sign the range of motion is too deep for the load.',
  'Keep your core braced and lower back pinned to the pad throughout the set.',
  '10–15 reps', '90 sec–2 min', '2-1-2 tempo',
  'Focus on pushing through your whole foot, not just your toes.'),
('Bulgarian Split Squat', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Rear foot elevated on a bench, front foot far enough forward that your front shin stays close to vertical.',
  'Lower straight down until your back knee is near the floor, then drive up through your front foot.',
  'Placing the front foot too close to the bench forces the front knee too far forward and shifts the emphasis away from the glutes/hamstrings.',
  'Keep your torso tall and core tight — this is a balance-heavy movement, and a loose core makes it worse.',
  '8–12 reps per leg', '90 sec', '2-1-2 tempo',
  'Feel the stretch in your front-leg glute at the bottom before driving up.'),
('Walking Lunge', 'Legs', 'quads', '{glutes,hamstrings}', 'Dumbbell',
  'Stand tall holding dumbbells at your sides or a bar on your back.',
  'Step forward into a lunge, lowering your back knee toward the floor, then drive through your front foot to step into the next rep.',
  'Taking too short a step turns it into a knee-dominant exercise and adds unnecessary knee stress.',
  'Keep your torso upright and core braced — leaning forward shifts the work away from your legs and onto your lower back.',
  '10–15 reps per leg', '90 sec', 'controlled 2 sec descent per step',
  'Push the ground away from you with your front foot rather than pushing off your back foot.'),
('Reverse Lunge', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Stand tall holding dumbbells at your sides or a bar on your back.',
  'Step backward into a lunge, lowering your back knee toward the floor, then drive through your front foot to return to standing.',
  'Letting the front knee cave inward as you drive back up.',
  'Keep your torso upright and core braced throughout the step.',
  '10–15 reps per leg', '90 sec', '2-1-2 tempo',
  'Think about driving through your front heel to stand back up, not pushing off your back foot.'),
('Leg Extension', 'Legs', 'quads', '{}', 'Machine',
  'Sit with the pad resting just above your ankles, back against the seat.',
  'Extend your knees until your legs are straight, then lower back under control.',
  'Using momentum to kick the weight up at the top instead of a controlled extension through the full range.',
  'Keep your back against the pad and grip the seat handles to keep your upper body still.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Squeeze and hold at the top for a full second before lowering.'),
('Hip Thrust', 'Legs', 'glutes', '{hamstrings}', 'Barbell',
  'Upper back braced against a bench, bar across your hips, feet flat roughly shoulder width.',
  'Drive your hips up until your torso is roughly in line with your thighs, squeezing your glutes hard at the top.',
  'Overextending the lower back at the top to gain a few extra inches instead of stopping at a straight hip-to-shoulder line.',
  'Tuck your chin slightly and brace your abs at the top of each rep to avoid an exaggerated lower-back arch.',
  '8–15 reps', '90 sec–2 min', '1-2-1 tempo — pause and squeeze at the top',
  'Squeeze your glutes as hard as you can at the top, holding for a full second.'),
('Step-Up', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Stand facing a box or bench roughly knee height, dumbbells at your sides.',
  'Step up onto the box leading with one foot, driving through that leg to stand fully on top, then step back down under control.',
  'Pushing off the bottom leg to help you up instead of driving through the top leg.',
  'Keep your torso upright and place your whole foot on the box, not just your toes.',
  '10–15 reps per leg', '90 sec', 'controlled 2 sec down',
  'Focus all the driving effort through the leg that''s on the box.'),

-- ── Legs: Hamstrings/Posterior Chain ────────────────────────────────────
('Stiff-Leg Deadlift', 'Legs', 'hamstrings', '{glutes,back}', 'Barbell',
  'Similar to a Romanian deadlift but with straighter (though not locked) knees, bar at hip height.',
  'Lower the bar along your legs by hinging at the hips until you feel a deep hamstring stretch, then drive your hips forward to stand.',
  'Locking the knees completely, which can strain the lower back and reduce hamstring involvement.',
  'Keep a flat back and braced core throughout — the range of motion is often shorter than an RDL since the legs stay straighter.',
  '8–12 reps', '90 sec–2 min', '3-1-1 tempo',
  'Focus on the stretch in your hamstrings as the primary signal, not how low the bar goes.'),
('Leg Curl', 'Legs', 'hamstrings', '{}', 'Machine',
  'Lie face down (or seated, depending on the machine) with the pad positioned just above your heels.',
  'Curl your heels toward your glutes, then lower back under control without letting the weight stack slam.',
  'Using a big hip lift to help the weight up instead of isolating the hamstrings — keep your hips pinned down.',
  'Keep your hips pressed into the pad/bench throughout the movement.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Curl your heels toward your glutes and squeeze hard at the top.'),
('Good Morning', 'Legs', 'hamstrings', '{glutes,back}', 'Barbell',
  'Bar on your upper back like a squat, feet shoulder width, soft bend in the knees.',
  'Hinge forward at the hips, keeping your back flat, until your torso is near parallel to the floor, then drive your hips forward to stand.',
  'Rounding the lower back as you hinge forward instead of keeping it flat and neutral.',
  'Brace your core hard before descending — this is one of the least forgiving lifts for a loose back.',
  '8–12 reps (start light — this movement has a steep learning curve)', '90 sec–2 min', 'controlled 2-3 sec hinge down',
  'Feel your hamstrings load up as you hinge, treating your hips as the hinge point, not your spine.'),
('Nordic Curl', 'Legs', 'hamstrings', '{}', 'Bodyweight',
  'Kneel with your ankles secured (partner holding them or under a pad), torso upright.',
  'Lower your torso toward the floor as slowly as possible by resisting with your hamstrings, catching yourself with your hands at the bottom, then use your hamstrings and hands to return.',
  'Letting the hips pike or bend forward instead of keeping a straight line from knees to head.',
  'Brace your core and glutes to keep your body in one straight line as you lower.',
  '3–8 reps (an advanced, eccentric-only movement for most lifters)', '90 sec–2 min', 'as slow as possible on the way down',
  'Fight the fall the entire way down — the slower you resist, the more it''s working.'),
('Glute Bridge', 'Legs', 'glutes', '{hamstrings}', 'Bodyweight',
  'Lie on your back, knees bent, feet flat on the floor close to your glutes.',
  'Drive your hips up until your body forms a straight line from shoulders to knees, squeeze, then lower under control.',
  'Overarching the lower back at the top instead of stopping at a straight hip-to-shoulder line.',
  'Brace your abs at the top of each rep to avoid compensating with your lower back.',
  '12–20 reps', '60 sec', '1-2-1 tempo — pause and squeeze at the top',
  'Squeeze your glutes, not your lower back, to lift your hips.'),

-- ── Calves ─────────────────────────────────────────────────────────────
('Standing Calf Raise', 'Legs', 'calves', '{}', 'Machine',
  'Stand on a raised edge or platform with your heels hanging off, balls of your feet planted.',
  'Rise up onto your toes as high as possible, pause briefly, then lower your heels below the platform for a full stretch.',
  'Using short, bouncy reps instead of a full stretch at the bottom and a full contraction at the top — most of the benefit is in that full range.',
  'Keep your knees roughly straight (soft, not locked) so the calves — not the knees — are doing the work.',
  '12–20 reps', '60 sec', '2-1-2 tempo — full stretch, full contraction',
  'Rise as high onto your toes as possible and hold the squeeze briefly.'),
('Seated Calf Raise', 'Legs', 'calves', '{}', 'Machine',
  'Sit with the balls of your feet on the platform, pad resting across your lower thighs.',
  'Rise up onto your toes as high as possible, pause, then lower your heels for a full stretch.',
  'Using a short, bouncy range of motion instead of the full stretch-to-contraction range.',
  'Keep your knees still under the pad — the movement should be isolated to your ankles.',
  '12–20 reps', '60 sec', '2-1-2 tempo',
  'The bent-knee position targets the soleus underneath the calf — focus on that deeper muscle working.'),
('Leg Press Calf Raise', 'Legs', 'calves', '{}', 'Machine',
  'In the leg press machine, place just the balls of your feet on the lower edge of the platform, legs extended.',
  'Push through your toes to extend your ankles, then lower your heels for a full stretch.',
  'Bending the knees to help push the weight instead of isolating the ankle movement.',
  'Keep your knees locked in a fixed, slightly-bent position throughout — only your ankles should move.',
  '12–20 reps', '60 sec', '2-1-2 tempo',
  'Focus on pointing your toes as far as possible at the top of each rep.'),

-- ── Arms: Biceps ───────────────────────────────────────────────────────
('Barbell Curl', 'Pull', 'biceps', '{forearms}', 'Barbell',
  'Stand tall, grip shoulder width, elbows pinned to your sides.',
  'Curl the bar up by bending your elbows, keeping your upper arms still, then lower under control.',
  'Swinging the hips and leaning back to heave the weight up — it takes the tension off the biceps entirely.',
  'Keep your core tight and elbows locked in place so the only thing moving is your forearms.',
  '8–12 reps', '60–90 sec', '2-1-2 tempo',
  'Squeeze your bicep hard at the top rather than just reaching the top position.'),
('Dumbbell Curl', 'Pull', 'biceps', '{forearms}', 'Dumbbell',
  'Stand or sit with dumbbells at your sides, palms facing forward or neutral.',
  'Curl one or both dumbbells up, optionally rotating to a full supination at the top, then lower under control.',
  'Letting the elbow drift forward as the weight gets heavy, which lets the front delt take over the movement.',
  'Keep your upper arm pinned against your torso throughout the rep.',
  '10–12 reps', '60–90 sec', '2-1-2 tempo',
  'Rotate your palm fully up as you curl to get a full bicep contraction.'),
('Hammer Curl', 'Pull', 'biceps', '{forearms}', 'Dumbbell',
  'Stand or sit with dumbbells at your sides, palms facing your body (neutral grip).',
  'Curl the dumbbells up keeping the neutral grip throughout, then lower under control.',
  'Letting the elbows drift forward as the weight gets heavy, reducing bicep/forearm tension.',
  'Keep your upper arms pinned to your sides throughout the movement.',
  '10–12 reps', '60–90 sec', '2-1-2 tempo',
  'This grip emphasizes the brachialis and forearm — focus on the outer arm working, not just the bicep peak.'),
('Preacher Curl', 'Pull', 'biceps', '{forearms}', 'Barbell',
  'Rest your upper arms on the preacher bench pad, grip the bar or dumbbells with arms extended.',
  'Curl the weight up, then lower under control until your arms are nearly straight.',
  'Not lowering all the way, cutting off the stretch portion where preacher curls are most valuable.',
  'Keep your chest against the pad and avoid lifting your upper arms off it to cheat the weight up.',
  '10–12 reps', '60–90 sec', '3-1-1 tempo — slow on the stretch',
  'Focus on the deep stretch at the bottom — that''s what makes this variation valuable.'),
('Cable Curl', 'Pull', 'biceps', '{forearms}', 'Cable',
  'Stand facing a low cable pulley, grip the bar or handle with arms extended.',
  'Curl the handle up toward your shoulders, then lower under control.',
  'Leaning back to use body momentum instead of isolating the biceps.',
  'Keep your torso upright and elbows pinned to your sides — the cable''s constant tension makes cheating more obvious.',
  '10–15 reps', '60 sec', '2-1-2 tempo',
  'Notice the constant tension through the whole range, especially at the bottom where dumbbells lose it.'),
('Incline Dumbbell Curl', 'Pull', 'biceps', '{forearms}', 'Dumbbell',
  'Sit on an incline bench (45–60°), let your arms hang straight down, palms forward.',
  'Curl the dumbbells up without letting your elbows drift forward, then lower under control.',
  'Letting the shoulders round forward to shorten the range instead of getting the full stretch.',
  'Keep your shoulders pinned back against the bench throughout.',
  '10–12 reps', '60–90 sec', '3-1-1 tempo',
  'The behind-the-torso arm position maximizes the stretch — focus on feeling that deep stretch at the bottom.'),
('Concentration Curl', 'Pull', 'biceps', '{}', 'Dumbbell',
  'Sit on a bench, brace your elbow against the inside of your thigh, dumbbell hanging below.',
  'Curl the dumbbell up toward your shoulder, then lower under control.',
  'Letting the elbow drift off the thigh, which lets other muscles assist the lift.',
  'Keep your elbow locked against your thigh throughout the entire set.',
  '10–15 reps', '60 sec', '2-1-2 tempo',
  'With the arm fully isolated, this is the easiest exercise to really feel the bicep working — pay attention to that.'),

-- ── Arms: Triceps ──────────────────────────────────────────────────────
('Close-Grip Bench Press', 'Push', 'triceps', '{chest}', 'Barbell',
  'Grip just inside shoulder width, elbows tucked close to your sides.',
  'Lower the bar to your lower chest keeping elbows tracking straight back, then press up.',
  'Gripping too narrow (hands touching) puts unnecessary strain on the wrists without adding tricep benefit.',
  'Same full-body brace as a regular bench — feet driving down, upper back tight against the bench.',
  '8–12 reps', '90 sec–2 min', '2-1-1 tempo',
  'Keep your elbows tucked and think about pressing straight up, not out.'),
('Tricep Pushdown', 'Push', 'triceps', '{}', 'Cable',
  'Grip the bar or rope with elbows pinned to your sides, standing tall.',
  'Extend your forearms down until your arms are straight, then control the weight back up.',
  'Letting the elbows drift forward or flare out turns this into a shoulder/chest movement instead of isolating the triceps.',
  'Keep your torso still — using body momentum to help the weight down is the most common way to cheat this exercise.',
  '10–15 reps', '60 sec', '2-1-2 tempo',
  'Squeeze and fully extend your arms at the bottom, holding briefly.'),
('Overhead Tricep Extension', 'Push', 'triceps', '{}', 'Dumbbell',
  'Sit or stand holding a dumbbell with both hands overhead, elbows pointed forward.',
  'Lower the dumbbell behind your head by bending the elbows, then extend back to straight arms.',
  'Letting the elbows flare out wide instead of staying pointed forward throughout.',
  'Keep your core braced and ribs down so you''re not overarching your lower back to compensate.',
  '10–15 reps', '60–90 sec', '3-1-1 tempo',
  'Focus on the stretch in your triceps at the bottom of the movement.'),
('Skull Crusher', 'Push', 'triceps', '{}', 'Barbell',
  'Lie on a flat bench, bar held with arms extended straight up over your chest.',
  'Bend your elbows to lower the bar toward your forehead (or just behind it), then extend back up.',
  'Letting the elbows flare out or drift back over the face, increasing shoulder strain.',
  'Keep your upper arms vertical and stationary — only your forearms should move.',
  '10–12 reps', '60–90 sec', '2-1-1 tempo',
  'Keep the movement isolated to your elbow joint, feeling the stretch as the bar lowers.'),
('Dip (Tricep-Focused)', 'Push', 'triceps', '{chest}', 'Bodyweight',
  'Grip the bars with arms straight, keep your torso upright rather than leaning forward.',
  'Lower until your elbows reach about 90°, then press back up, keeping the upright torso.',
  'Leaning forward, which shifts emphasis to the chest instead of the triceps.',
  'Keep your core braced and torso as vertical as possible throughout.',
  '8–15 reps (add weight once bodyweight gets easy)', '90 sec', '2-1-1 tempo',
  'Keep your elbows tracking straight back, close to your body, throughout the movement.'),
('Kickback', 'Push', 'triceps', '{}', 'Dumbbell',
  'Hinge forward at the hips, upper arm parallel to the floor, elbow bent at 90°, dumbbell in hand.',
  'Extend your arm straight back until it''s fully extended, then return to the bent position.',
  'Swinging the weight using shoulder momentum instead of isolating the elbow extension.',
  'Keep your upper arm pinned parallel to the floor throughout — only your forearm should move.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Squeeze and hold the full extension for a full second before returning.'),

-- ── Core ───────────────────────────────────────────────────────────────
('Plank', 'Core', 'abs', '{}', 'Bodyweight',
  'Forearms on the floor under your shoulders, body in a straight line from head to heels.',
  'Hold the position, breathing normally, keeping your hips level — neither sagging nor piking up.',
  'Letting the hips sag toward the floor as fatigue sets in, which shifts the load onto the lower back instead of the abs.',
  'Actively squeeze your abs and glutes throughout — a plank is an active brace, not just a static hold.',
  '30–60 sec holds, 2–4 sets', '45–60 sec', 'n/a — isometric hold',
  'Actively brace and squeeze the entire time — don''t just "rest" in the position.'),
('Hanging Leg Raise', 'Core', 'abs', '{forearms}', 'Bodyweight',
  'Hang from a bar with a full grip, legs extended or knees bent depending on your level.',
  'Curl your hips up and raise your legs (or knees) toward your chest, then lower under control without swinging.',
  'Using momentum from a swing to fling the legs up instead of a controlled hip curl driven by the abs.',
  'Keep your ribs pulled down toward your pelvis throughout — an arched lower back means the hip flexors are taking over from the abs.',
  '10–15 reps', '60–90 sec', '2-1-2 tempo',
  'Focus on curling your pelvis up, not just swinging your legs forward.'),
('Cable Crunch', 'Core', 'abs', '{}', 'Cable',
  'Kneel below a high cable pulley, rope held beside your head, hips stacked over knees.',
  'Crunch your torso down and in, bringing your elbows toward your thighs, then return under control.',
  'Bending only at the hips instead of actually flexing/crunching the spine.',
  'Keep your hips relatively still — the movement should come from spinal flexion, not a hip hinge.',
  '12–20 reps', '60 sec', '2-1-2 tempo',
  'Think about rounding your spine and bringing your ribcage toward your hips.'),
('Ab Wheel Rollout', 'Core', 'abs', '{shoulders}', 'Bodyweight',
  'Kneel on a pad, hands gripping the wheel directly under your shoulders.',
  'Roll forward as far as you can control, keeping your core braced, then pull back to the start using your abs, not your arms.',
  'Letting the lower back sag as you roll out — that''s usually the sign you''ve gone further than your current core strength supports.',
  'Brace your abs hard through the entire rollout — imagine trying to keep a flat line from your shoulders to your knees.',
  '8–15 reps', '60–90 sec', 'controlled, as slow as you can manage',
  'Brace hard the entire time — imagine trying to keep a flat line from shoulders to knees.'),
('Russian Twist', 'Core', 'abs', '{}', 'Bodyweight',
  'Sit with knees bent, lean back slightly to engage your core, feet can be lifted for more difficulty.',
  'Rotate your torso side to side, touching the floor (or a weight) beside your hip each time.',
  'Moving fast and using momentum instead of controlled rotation.',
  'Keep your core braced throughout — this should feel like controlled rotation, not a flailing twist.',
  '16–24 total reps (8–12 per side)', '45–60 sec', 'controlled, 1-2 sec per side',
  'Focus on rotating from your ribcage, not just swinging your arms.'),
('Weighted Sit-Up', 'Core', 'abs', '{}', 'Dumbbell',
  'Lie on your back, knees bent, feet anchored if needed, weight held at your chest.',
  'Sit all the way up by flexing your spine and hips, then lower back down under control.',
  'Using momentum to fling yourself up instead of controlling the movement.',
  'Keep the weight close to your chest throughout to avoid straining your lower back.',
  '10–15 reps', '60 sec', '2-1-2 tempo',
  'Lead with your chest curling toward your knees, not your head jerking forward.'),
('Pallof Press', 'Core', 'abs', '{}', 'Cable',
  'Stand sideways to a cable pulley at chest height, hold the handle at your chest with both hands.',
  'Press the handle straight out in front of you, resisting the cable''s pull to rotate you, then bring it back.',
  'Letting your torso rotate toward the machine instead of resisting the pull.',
  'Brace your core hard to keep your hips and shoulders square the entire time.',
  '10–15 reps per side', '45–60 sec', '2-1-2 tempo',
  'This is an anti-rotation exercise — the goal is to feel your core working to prevent movement, not create it.'),

-- ── Full Body / Compound-Adjacent ────────────────────────────────────────
('Clean', 'Full Body', null, '{back,quads,shoulders}', 'Barbell',
  'Bar over mid-foot, grip just outside shoulder width, hips higher than knees, chest up.',
  'Pull the bar explosively from the floor, extending fully through the hips, then drop under it to catch it in a front-rack position on your shoulders.',
  'Pulling with the arms too early instead of driving the explosive extension through the hips first.',
  'Brace hard off the floor, then reset that brace quickly to absorb the catch.',
  '3–5 reps (technique/power focused, not typically programmed for hypertrophy)', '2–3 min', 'explosive — this is a power movement, not a slow-tempo one',
  'Focus on explosive hip extension — this lift is about speed and technique, not a muscle-feel cue.'),
('Power Clean', 'Full Body', null, '{back,quads,shoulders}', 'Barbell',
  'Bar over mid-foot, same starting position as a deadlift, grip just outside shoulder width.',
  'Pull the bar explosively from the floor, extending through the hips as it passes your thighs, then drop under it to catch it on your front delts.',
  'Muscling the bar up with your arms early instead of using an explosive hip extension — the arms should stay relatively passive until the very end of the pull.',
  'Brace hard off the floor just like a deadlift, then reset that brace quickly to catch the bar in the front-rack position.',
  '3–5 reps (technique/power focused)', '2–3 min', 'explosive pull, controlled catch',
  'Same as the full Clean — the priority is explosive hip extension, not muscle feel.'),
('Clean and Jerk', 'Full Body', null, '{back,quads,shoulders}', 'Barbell',
  'Same starting position as a Clean; after catching the clean in the front rack, reset for the jerk.',
  'Complete the clean into the front rack, then dip slightly and drive the bar overhead, splitting or squatting your feet to catch it locked out.',
  'Pressing the bar up with the arms during the jerk instead of driving it up with a leg dip-and-drive.',
  'Re-brace fully between the clean and the jerk — treat them as two separate, fully-braced efforts.',
  '1–3 reps (a technical, high-skill lift; not a hypertrophy-focused exercise)', '3 min+', 'explosive throughout',
  'This is a technique and power lift — prioritize the movement pattern over any muscle-feel cue.'),
('Snatch', 'Full Body', null, '{back,shoulders,quads}', 'Barbell',
  'Wide grip, bar over mid-foot, similar starting position to a deadlift/clean but with hands further apart.',
  'Pull the bar explosively from the floor directly overhead in one motion, dropping under it to catch in a full overhead squat position.',
  'Muscling the bar up with the arms instead of using an explosive hip extension to give it upward speed.',
  'This requires a strong, stable overhead position — brace your entire torso hard on the catch.',
  '1–3 reps (highly technical; requires coaching before adding load)', '3 min+', 'explosive',
  'Like the Clean, this is about speed and timing, not a hypertrophy muscle-feel cue.'),
('Farmer''s Carry', 'Full Body', null, '{forearms,back,abs}', 'Dumbbell',
  'Stand between two heavy dumbbells or a trap bar, grip firmly, stand up tall.',
  'Walk forward for a set distance or time, keeping your torso upright and shoulders back.',
  'Letting the shoulders round forward or the weight pull you into a lean as you fatigue.',
  'Brace your core like you''re about to be hit, and keep your grip locked in throughout.',
  '20–40 sec (or 20–40 yards) per set', '60–90 sec', 'steady, controlled walking pace',
  'Focus on staying tall and stable — this is as much a bracing/grip exercise as it is a leg/conditioning one.'),
('Thruster', 'Full Body', null, '{quads,shoulders}', 'Barbell',
  'Bar in a front-rack position (like a front squat), feet shoulder width.',
  'Squat down, then use the upward drive out of the squat to press the bar overhead in one continuous motion.',
  'Pausing between the squat and the press instead of using the leg drive to help the press.',
  'Brace hard before descending — you''ll need that same brace to support the overhead press right after.',
  '8–15 reps (often used for conditioning/metabolic work more than pure hypertrophy)', '60–90 sec', 'continuous — squat and press blend into one fluid motion',
  'Feel the momentum from your legs carrying directly into the press — it shouldn''t feel like two separate movements.');
