-- Krafft — Phase 17 (part 5 of 5): exercise library expansion + hypertrophy guidance.
-- Run this after part 4. See part 1 for the full explanation.

insert into exercises (name, muscle_group, body_region, secondary_regions, equipment, cue_setup, cue_execution, cue_mistake, cue_bracing, hypertrophy_rep_range, hypertrophy_rest_interval, hypertrophy_tempo, hypertrophy_mind_muscle_cue) values
('Dip (Tricep-Focused)', 'Push', 'triceps', '{chest}', 'Bodyweight',
  'Grip the bars with arms straight, keep your torso upright rather than leaning forward.',
  'Lower until your elbows reach about 90°, then press back up, keeping the upright torso.',
  'Leaning forward, which shifts emphasis to the chest instead of the triceps.',
  'Keep your core braced and torso as vertical as possible throughout.',
  '8–15 reps (add weight once bodyweight gets easy)', '90 sec', '2-1-1 tempo',
  'Keep your elbows tracking straight back, close to your body, throughout the movement.'),
('Kickback', 'Push', 'triceps', '{}', 'Dumbbell',
  'Hinge forward at the hips, upper arm parallel to the floor, elbow bent at 90°, dumbbell in hand.',
  'Extend your arm straight back until it''s fully extended, then return to the bent position.',
  'Swinging the weight using shoulder momentum instead of isolating the elbow extension.',
  'Keep your upper arm pinned parallel to the floor throughout — only your forearm should move.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Squeeze and hold the full extension for a full second before returning.'),
('Plank', 'Core', 'abs', '{}', 'Bodyweight',
  'Forearms on the floor under your shoulders, body in a straight line from head to heels.',
  'Hold the position, breathing normally, keeping your hips level — neither sagging nor piking up.',
  'Letting the hips sag toward the floor as fatigue sets in, which shifts the load onto the lower back instead of the abs.',
  'Actively squeeze your abs and glutes throughout — a plank is an active brace, not just a static hold.',
  '30–60 sec holds, 2–4 sets', '45–60 sec', 'n/a — isometric hold',
  'Actively brace and squeeze the entire time — don''t just "rest" in the position.'),
('Hanging Leg Raise', 'Core', 'abs', '{forearms}', 'Bodyweight',
  'Hang from a bar with a full grip, legs extended or knees bent depending on your level.',
  'Curl your hips up and raise your legs (or knees) toward your chest, then lower under control without swinging.',
  'Using momentum from a swing to fling the legs up instead of a controlled hip curl driven by the abs.',
  'Keep your ribs pulled down toward your pelvis throughout — an arched lower back means the hip flexors are taking over from the abs.',
  '10–15 reps', '60–90 sec', '2-1-2 tempo',
  'Focus on curling your pelvis up, not just swinging your legs forward.'),
('Cable Crunch', 'Core', 'abs', '{}', 'Cable',
  'Kneel below a high cable pulley, rope held beside your head, hips stacked over knees.',
  'Crunch your torso down and in, bringing your elbows toward your thighs, then return under control.',
  'Bending only at the hips instead of actually flexing/crunching the spine.',
  'Keep your hips relatively still — the movement should come from spinal flexion, not a hip hinge.',
  '12–20 reps', '60 sec', '2-1-2 tempo',
  'Think about rounding your spine and bringing your ribcage toward your hips.'),
('Ab Wheel Rollout', 'Core', 'abs', '{shoulders}', 'Bodyweight',
  'Kneel on a pad, hands gripping the wheel directly under your shoulders.',
  'Roll forward as far as you can control, keeping your core braced, then pull back to the start using your abs, not your arms.',
  'Letting the lower back sag as you roll out — that''s usually the sign you''ve gone further than your current core strength supports.',
  'Brace your abs hard through the entire rollout — imagine trying to keep a flat line from your shoulders to your knees.',
  '8–15 reps', '60–90 sec', 'controlled, as slow as you can manage',
  'Brace hard the entire time — imagine trying to keep a flat line from shoulders to knees.'),
('Russian Twist', 'Core', 'abs', '{}', 'Bodyweight',
  'Sit with knees bent, lean back slightly to engage your core, feet can be lifted for more difficulty.',
  'Rotate your torso side to side, touching the floor (or a weight) beside your hip each time.',
  'Moving fast and using momentum instead of controlled rotation.',
  'Keep your core braced throughout — this should feel like controlled rotation, not a flailing twist.',
  '16–24 total reps (8–12 per side)', '45–60 sec', 'controlled, 1-2 sec per side',
  'Focus on rotating from your ribcage, not just swinging your arms.'),
('Weighted Sit-Up', 'Core', 'abs', '{}', 'Dumbbell',
  'Lie on your back, knees bent, feet anchored if needed, weight held at your chest.',
  'Sit all the way up by flexing your spine and hips, then lower back down under control.',
  'Using momentum to fling yourself up instead of controlling the movement.',
  'Keep the weight close to your chest throughout to avoid straining your lower back.',
  '10–15 reps', '60 sec', '2-1-2 tempo',
  'Lead with your chest curling toward your knees, not your head jerking forward.'),
('Pallof Press', 'Core', 'abs', '{}', 'Cable',
  'Stand sideways to a cable pulley at chest height, hold the handle at your chest with both hands.',
  'Press the handle straight out in front of you, resisting the cable''s pull to rotate you, then bring it back.',
  'Letting your torso rotate toward the machine instead of resisting the pull.',
  'Brace your core hard to keep your hips and shoulders square the entire time.',
  '10–15 reps per side', '45–60 sec', '2-1-2 tempo',
  'This is an anti-rotation exercise — the goal is to feel your core working to prevent movement, not create it.'),
('Clean', 'Full Body', null, '{back,quads,shoulders}', 'Barbell',
  'Bar over mid-foot, grip just outside shoulder width, hips higher than knees, chest up.',
  'Pull the bar explosively from the floor, extending fully through the hips, then drop under it to catch it in a front-rack position on your shoulders.',
  'Pulling with the arms too early instead of driving the explosive extension through the hips first.',
  'Brace hard off the floor, then reset that brace quickly to absorb the catch.',
  '3–5 reps (technique/power focused, not typically programmed for hypertrophy)', '2–3 min', 'explosive — this is a power movement, not a slow-tempo one',
  'Focus on explosive hip extension — this lift is about speed and technique, not a muscle-feel cue.'),
('Power Clean', 'Full Body', null, '{back,quads,shoulders}', 'Barbell',
  'Bar over mid-foot, same starting position as a deadlift, grip just outside shoulder width.',
  'Pull the bar explosively from the floor, extending through the hips as it passes your thighs, then drop under it to catch it on your front delts.',
  'Muscling the bar up with your arms early instead of using an explosive hip extension — the arms should stay relatively passive until the very end of the pull.',
  'Brace hard off the floor just like a deadlift, then reset that brace quickly to catch the bar in the front-rack position.',
  '3–5 reps (technique/power focused)', '2–3 min', 'explosive pull, controlled catch',
  'Same as the full Clean — the priority is explosive hip extension, not muscle feel.'),
('Clean and Jerk', 'Full Body', null, '{back,quads,shoulders}', 'Barbell',
  'Same starting position as a Clean; after catching the clean in the front rack, reset for the jerk.',
  'Complete the clean into the front rack, then dip slightly and drive the bar overhead, splitting or squatting your feet to catch it locked out.',
  'Pressing the bar up with the arms during the jerk instead of driving it up with a leg dip-and-drive.',
  'Re-brace fully between the clean and the jerk — treat them as two separate, fully-braced efforts.',
  '1–3 reps (a technical, high-skill lift; not a hypertrophy-focused exercise)', '3 min+', 'explosive throughout',
  'This is a technique and power lift — prioritize the movement pattern over any muscle-feel cue.'),
('Snatch', 'Full Body', null, '{back,shoulders,quads}', 'Barbell',
  'Wide grip, bar over mid-foot, similar starting position to a deadlift/clean but with hands further apart.',
  'Pull the bar explosively from the floor directly overhead in one motion, dropping under it to catch in a full overhead squat position.',
  'Muscling the bar up with the arms instead of using an explosive hip extension to give it upward speed.',
  'This requires a strong, stable overhead position — brace your entire torso hard on the catch.',
  '1–3 reps (highly technical; requires coaching before adding load)', '3 min+', 'explosive',
  'Like the Clean, this is about speed and timing, not a hypertrophy muscle-feel cue.'),
('Farmer''s Carry', 'Full Body', null, '{forearms,back,abs}', 'Dumbbell',
  'Stand between two heavy dumbbells or a trap bar, grip firmly, stand up tall.',
  'Walk forward for a set distance or time, keeping your torso upright and shoulders back.',
  'Letting the shoulders round forward or the weight pull you into a lean as you fatigue.',
  'Brace your core like you''re about to be hit, and keep your grip locked in throughout.',
  '20–40 sec (or 20–40 yards) per set', '60–90 sec', 'steady, controlled walking pace',
  'Focus on staying tall and stable — this is as much a bracing/grip exercise as it is a leg/conditioning one.'),
('Thruster', 'Full Body', null, '{quads,shoulders}', 'Barbell',
  'Bar in a front-rack position (like a front squat), feet shoulder width.',
  'Squat down, then use the upward drive out of the squat to press the bar overhead in one continuous motion.',
  'Pausing between the squat and the press instead of using the leg drive to help the press.',
  'Brace hard before descending — you''ll need that same brace to support the overhead press right after.',
  '8–15 reps (often used for conditioning/metabolic work more than pure hypertrophy)', '60–90 sec', 'continuous — squat and press blend into one fluid motion',
  'Feel the momentum from your legs carrying directly into the press — it shouldn''t feel like two separate movements.');
