-- Krafft — Phase 17 (part 2 of 5): exercise library expansion + hypertrophy guidance.
-- Run this after part 1. See part 1 for the full explanation.

insert into exercises (name, muscle_group, body_region, secondary_regions, equipment, cue_setup, cue_execution, cue_mistake, cue_bracing, hypertrophy_rep_range, hypertrophy_rest_interval, hypertrophy_tempo, hypertrophy_mind_muscle_cue) values
('T-Bar Row', 'Pull', 'back', '{biceps,forearms}', 'Barbell',
  'Straddle the bar with a chest pad or hinge over it, grip the handles with a neutral or wide grip.',
  'Pull the weight up to your torso, squeezing your shoulder blades together, then lower under control.',
  'Using a short, jerky range of motion instead of a full stretch-to-squeeze pull.',
  'Keep your chest against the pad (if using one) or your hinge position fixed throughout.',
  '8–12 reps', '90 sec–2 min', '1-1-2 tempo',
  'Focus on pulling your shoulder blades together, not just bending your elbows.'),
('Seated Cable Row', 'Pull', 'back', '{biceps,forearms}', 'Cable',
  'Sit with knees slightly bent, back tall, grip the handle with arms extended.',
  'Pull the handle to your torso, squeezing your shoulder blades together, then extend back out under control.',
  'Rounding your lower back to add a few extra inches of pull range instead of keeping a tall, stable torso.',
  'Keep your torso upright and braced throughout — the movement should come from your arms and shoulder blades, not your spine rocking.',
  '10–12 reps', '90 sec', '1-1-2 tempo',
  'Lead the pull with your chest moving toward the handle, not just your arms bending.'),
('Lat Pulldown', 'Pull', 'back', '{biceps}', 'Cable',
  'Grip slightly wider than shoulder width, sit tall with thighs secured under the pad.',
  'Pull the bar to your upper chest, driving your elbows down and back, then control it back up.',
  'Leaning back excessively and using body weight instead of your back muscles to move the bar.',
  'Keep your chest up and core braced — a small, controlled lean is fine, but a big swing is momentum, not strength.',
  '10–12 reps', '90 sec', '1-1-2 tempo',
  'Think about pulling your elbows down toward your back pockets.'),
('Pull-Up', 'Pull', 'back', '{biceps,forearms}', 'Bodyweight',
  'Grip just outside shoulder width, palms facing away, hang with arms fully extended.',
  'Pull your chin over the bar leading with your chest, then lower back to a full hang under control.',
  'Only doing the top half of the rep (partial range) trains less muscle and builds strength you can''t actually use.',
  'Keep a slight hollow-body brace so you''re not using an uncontrolled kip or swing to gain momentum.',
  '6–12 reps (add weight once bodyweight gets easy)', '90 sec–2 min', '1-1-2 tempo',
  'Drive your elbows down and back rather than just pulling with your hands.'),
('Chin-Up', 'Pull', 'back', '{biceps}', 'Bodyweight',
  'Grip shoulder width, palms facing you, hang with arms fully extended.',
  'Pull yourself up until your chin clears the bar, then lower back down under control.',
  'Turning it into a chest-up crunch instead of a straight vertical pull reduces the actual back/bicep work.',
  'Keep your ribs down and core tight to avoid an excessive arch through your lower back.',
  '6–12 reps', '90 sec–2 min', '1-1-2 tempo',
  'Feel your lats stretch fully at the bottom before initiating the next pull.'),
('Straight-Arm Pulldown', 'Pull', 'back', '{abs}', 'Cable',
  'Stand facing a high cable pulley, grip a straight bar or rope with arms extended overhead.',
  'Keeping your arms mostly straight, pull the bar down in an arc to your thighs, then let it return.',
  'Bending the elbows significantly, which turns this into a tricep pushdown instead of a lat isolation move.',
  'Keep a slight forward hinge at the hips and brace your core so the movement comes from the shoulder, not the back.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Imagine pulling an imaginary bar down and back toward your hips in a wide arc.'),
('Face Pull', 'Pull', 'shoulders', '{back}', 'Cable',
  'Set the cable at roughly face height, grip the rope with palms facing in.',
  'Pull the rope toward your face, flaring your elbows out wide and rotating your hands back.',
  'Pulling with too much weight and turning it into a row instead of a high-elbow rear-delt/rotator cuff movement.',
  'Keep your upper back tight and shoulders down away from your ears throughout the pull.',
  '12–20 reps', '60 sec', '2-1-2 tempo',
  'Aim the rope toward your forehead and really flare your elbows wide at the end.'),
('Overhead Press', 'Push', 'shoulders', '{triceps,abs}', 'Barbell',
  'Grip just outside shoulder width, bar resting on your front delts, elbows slightly in front of the bar.',
  'Press straight up, moving your head back slightly to let the bar pass, then push your head through at the top.',
  'Leaning back excessively to help the bar clear your face turns this into an incline press and stresses the lower back.',
  'Squeeze your glutes and brace your abs like you''re about to be punched in the stomach — a loose torso leaks power.',
  '6–10 reps', '2 min', 'controlled 2 sec down, drive up with intent',
  'Push your head through at the top like you''re trying to look through a window above you.'),
('Seated Dumbbell Press', 'Push', 'shoulders', '{triceps}', 'Dumbbell',
  'Sit on a bench with back support, dumbbells at shoulder height, palms facing forward.',
  'Press the dumbbells up until arms are extended, then lower under control.',
  'Arching the lower back excessively to help push the weight overhead.',
  'Keep your back flat against the bench pad and core braced throughout.',
  '8–12 reps', '90 sec–2 min', '2-1-2 tempo',
  'Press the dumbbells up and slightly together, imagining you''re pressing through a narrow tube.'),
('Arnold Press', 'Push', 'shoulders', '{triceps}', 'Dumbbell',
  'Sit with dumbbells in front of your shoulders, palms facing you.',
  'As you press up, rotate your palms to face forward, finishing with arms extended overhead; reverse the rotation on the way down.',
  'Rushing the rotation instead of timing it smoothly with the press.',
  'Keep your core tight so the rotation doesn''t pull you off balance.',
  '8–12 reps', '90 sec', '2-1-2 tempo',
  'Feel the rotation take your front delt through a longer range than a standard press.'),
('Lateral Raise', 'Push', 'shoulders', '{}', 'Dumbbell',
  'Stand with a slight forward lean, dumbbells at your sides with a soft bend in the elbows.',
  'Raise the dumbbells out to the sides until roughly shoulder height, leading with your elbows.',
  'Using momentum to swing the weight up trains your traps more than your side delts — the target muscle.',
  'Keep your core braced so you''re not using a body swing to substitute for shoulder strength.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Lead with your elbows, not your hands, like you''re pouring water out of a jug at the top.'),
('Front Raise', 'Push', 'shoulders', '{}', 'Dumbbell',
  'Stand holding dumbbells at your thighs, palms facing your body or each other.',
  'Raise one or both dumbbells straight in front of you to shoulder height, then lower under control.',
  'Swinging the weight up using momentum from the hips and lower back.',
  'Keep your core braced and avoid leaning back to help lift the weight.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Focus on lifting with your front delt, not swinging from your torso.'),
('Rear Delt Fly', 'Pull', 'shoulders', '{back}', 'Dumbbell',
  'Hinge forward at the hips, dumbbells hanging below your shoulders, slight bend in the elbows.',
  'Raise the dumbbells out to the sides, squeezing your shoulder blades together, then lower under control.',
  'Standing too upright, which shifts the work to the upper traps instead of the rear delts.',
  'Keep your hinge position fixed and your core braced so you''re not using body momentum.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Imagine pulling your shoulder blades toward each other, not just raising your arms.'),
('Cable Lateral Raise', 'Push', 'shoulders', '{}', 'Cable',
  'Stand side-on to a low cable pulley, grip the handle across your body.',
  'Raise your arm out to the side to shoulder height, then lower under control.',
  'Using body lean to help swing the weight up instead of isolating the shoulder.',
  'Keep your torso upright and stable — the cable''s constant tension means less momentum is available to cheat with.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Feel constant tension through the whole range, especially at the bottom where dumbbells usually lose it.'),
('Upright Row', 'Pull', 'shoulders', '{back}', 'Barbell',
  'Stand holding a bar or dumbbells in front of your thighs, hands shoulder width or slightly closer.',
  'Pull the weight straight up along your body to roughly chest height, leading with your elbows, then lower under control.',
  'Pulling the bar too high or with a very narrow grip, which can aggravate the shoulder joint for some lifters.',
  'Keep your core braced and avoid using a big body heave to start the pull.',
  '10–15 reps', '60–90 sec', '2-1-2 tempo',
  'Think about leading the pull with your elbows staying above your hands throughout.');
