-- Krafft — Phase 17 (part 4 of 5): exercise library expansion + hypertrophy guidance.
-- Run this after part 3. See part 1 for the full explanation.

insert into exercises (name, muscle_group, body_region, secondary_regions, equipment, cue_setup, cue_execution, cue_mistake, cue_bracing, hypertrophy_rep_range, hypertrophy_rest_interval, hypertrophy_tempo, hypertrophy_mind_muscle_cue) values
('Glute Bridge', 'Legs', 'glutes', '{hamstrings}', 'Bodyweight',
  'Lie on your back, knees bent, feet flat on the floor close to your glutes.',
  'Drive your hips up until your body forms a straight line from shoulders to knees, squeeze, then lower under control.',
  'Overarching the lower back at the top instead of stopping at a straight hip-to-shoulder line.',
  'Brace your abs at the top of each rep to avoid compensating with your lower back.',
  '12–20 reps', '60 sec', '1-2-1 tempo — pause and squeeze at the top',
  'Squeeze your glutes, not your lower back, to lift your hips.'),
('Standing Calf Raise', 'Legs', 'calves', '{}', 'Machine',
  'Stand on a raised edge or platform with your heels hanging off, balls of your feet planted.',
  'Rise up onto your toes as high as possible, pause briefly, then lower your heels below the platform for a full stretch.',
  'Using short, bouncy reps instead of a full stretch at the bottom and a full contraction at the top — most of the benefit is in that full range.',
  'Keep your knees roughly straight (soft, not locked) so the calves — not the knees — are doing the work.',
  '12–20 reps', '60 sec', '2-1-2 tempo — full stretch, full contraction',
  'Rise as high onto your toes as possible and hold the squeeze briefly.'),
('Seated Calf Raise', 'Legs', 'calves', '{}', 'Machine',
  'Sit with the balls of your feet on the platform, pad resting across your lower thighs.',
  'Rise up onto your toes as high as possible, pause, then lower your heels for a full stretch.',
  'Using a short, bouncy range of motion instead of the full stretch-to-contraction range.',
  'Keep your knees still under the pad — the movement should be isolated to your ankles.',
  '12–20 reps', '60 sec', '2-1-2 tempo',
  'The bent-knee position targets the soleus underneath the calf — focus on that deeper muscle working.'),
('Leg Press Calf Raise', 'Legs', 'calves', '{}', 'Machine',
  'In the leg press machine, place just the balls of your feet on the lower edge of the platform, legs extended.',
  'Push through your toes to extend your ankles, then lower your heels for a full stretch.',
  'Bending the knees to help push the weight instead of isolating the ankle movement.',
  'Keep your knees locked in a fixed, slightly-bent position throughout — only your ankles should move.',
  '12–20 reps', '60 sec', '2-1-2 tempo',
  'Focus on pointing your toes as far as possible at the top of each rep.'),
('Barbell Curl', 'Pull', 'biceps', '{forearms}', 'Barbell',
  'Stand tall, grip shoulder width, elbows pinned to your sides.',
  'Curl the bar up by bending your elbows, keeping your upper arms still, then lower under control.',
  'Swinging the hips and leaning back to heave the weight up — it takes the tension off the biceps entirely.',
  'Keep your core tight and elbows locked in place so the only thing moving is your forearms.',
  '8–12 reps', '60–90 sec', '2-1-2 tempo',
  'Squeeze your bicep hard at the top rather than just reaching the top position.'),
('Dumbbell Curl', 'Pull', 'biceps', '{forearms}', 'Dumbbell',
  'Stand or sit with dumbbells at your sides, palms facing forward or neutral.',
  'Curl one or both dumbbells up, optionally rotating to a full supination at the top, then lower under control.',
  'Letting the elbow drift forward as the weight gets heavy, which lets the front delt take over the movement.',
  'Keep your upper arm pinned against your torso throughout the rep.',
  '10–12 reps', '60–90 sec', '2-1-2 tempo',
  'Rotate your palm fully up as you curl to get a full bicep contraction.'),
('Hammer Curl', 'Pull', 'biceps', '{forearms}', 'Dumbbell',
  'Stand or sit with dumbbells at your sides, palms facing your body (neutral grip).',
  'Curl the dumbbells up keeping the neutral grip throughout, then lower under control.',
  'Letting the elbows drift forward as the weight gets heavy, reducing bicep/forearm tension.',
  'Keep your upper arms pinned to your sides throughout the movement.',
  '10–12 reps', '60–90 sec', '2-1-2 tempo',
  'This grip emphasizes the brachialis and forearm — focus on the outer arm working, not just the bicep peak.'),
('Preacher Curl', 'Pull', 'biceps', '{forearms}', 'Barbell',
  'Rest your upper arms on the preacher bench pad, grip the bar or dumbbells with arms extended.',
  'Curl the weight up, then lower under control until your arms are nearly straight.',
  'Not lowering all the way, cutting off the stretch portion where preacher curls are most valuable.',
  'Keep your chest against the pad and avoid lifting your upper arms off it to cheat the weight up.',
  '10–12 reps', '60–90 sec', '3-1-1 tempo — slow on the stretch',
  'Focus on the deep stretch at the bottom — that''s what makes this variation valuable.'),
('Cable Curl', 'Pull', 'biceps', '{forearms}', 'Cable',
  'Stand facing a low cable pulley, grip the bar or handle with arms extended.',
  'Curl the handle up toward your shoulders, then lower under control.',
  'Leaning back to use body momentum instead of isolating the biceps.',
  'Keep your torso upright and elbows pinned to your sides — the cable''s constant tension makes cheating more obvious.',
  '10–15 reps', '60 sec', '2-1-2 tempo',
  'Notice the constant tension through the whole range, especially at the bottom where dumbbells lose it.'),
('Incline Dumbbell Curl', 'Pull', 'biceps', '{forearms}', 'Dumbbell',
  'Sit on an incline bench (45–60°), let your arms hang straight down, palms forward.',
  'Curl the dumbbells up without letting your elbows drift forward, then lower under control.',
  'Letting the shoulders round forward to shorten the range instead of getting the full stretch.',
  'Keep your shoulders pinned back against the bench throughout.',
  '10–12 reps', '60–90 sec', '3-1-1 tempo',
  'The behind-the-torso arm position maximizes the stretch — focus on feeling that deep stretch at the bottom.'),
('Concentration Curl', 'Pull', 'biceps', '{}', 'Dumbbell',
  'Sit on a bench, brace your elbow against the inside of your thigh, dumbbell hanging below.',
  'Curl the dumbbell up toward your shoulder, then lower under control.',
  'Letting the elbow drift off the thigh, which lets other muscles assist the lift.',
  'Keep your elbow locked against your thigh throughout the entire set.',
  '10–15 reps', '60 sec', '2-1-2 tempo',
  'With the arm fully isolated, this is the easiest exercise to really feel the bicep working — pay attention to that.'),
('Close-Grip Bench Press', 'Push', 'triceps', '{chest}', 'Barbell',
  'Grip just inside shoulder width, elbows tucked close to your sides.',
  'Lower the bar to your lower chest keeping elbows tracking straight back, then press up.',
  'Gripping too narrow (hands touching) puts unnecessary strain on the wrists without adding tricep benefit.',
  'Same full-body brace as a regular bench — feet driving down, upper back tight against the bench.',
  '8–12 reps', '90 sec–2 min', '2-1-1 tempo',
  'Keep your elbows tucked and think about pressing straight up, not out.'),
('Tricep Pushdown', 'Push', 'triceps', '{}', 'Cable',
  'Grip the bar or rope with elbows pinned to your sides, standing tall.',
  'Extend your forearms down until your arms are straight, then control the weight back up.',
  'Letting the elbows drift forward or flare out turns this into a shoulder/chest movement instead of isolating the triceps.',
  'Keep your torso still — using body momentum to help the weight down is the most common way to cheat this exercise.',
  '10–15 reps', '60 sec', '2-1-2 tempo',
  'Squeeze and fully extend your arms at the bottom, holding briefly.'),
('Overhead Tricep Extension', 'Push', 'triceps', '{}', 'Dumbbell',
  'Sit or stand holding a dumbbell with both hands overhead, elbows pointed forward.',
  'Lower the dumbbell behind your head by bending the elbows, then extend back to straight arms.',
  'Letting the elbows flare out wide instead of staying pointed forward throughout.',
  'Keep your core braced and ribs down so you''re not overarching your lower back to compensate.',
  '10–15 reps', '60–90 sec', '3-1-1 tempo',
  'Focus on the stretch in your triceps at the bottom of the movement.'),
('Skull Crusher', 'Push', 'triceps', '{}', 'Barbell',
  'Lie on a flat bench, bar held with arms extended straight up over your chest.',
  'Bend your elbows to lower the bar toward your forehead (or just behind it), then extend back up.',
  'Letting the elbows flare out or drift back over the face, increasing shoulder strain.',
  'Keep your upper arms vertical and stationary — only your forearms should move.',
  '10–12 reps', '60–90 sec', '2-1-1 tempo',
  'Keep the movement isolated to your elbow joint, feeling the stretch as the bar lowers.');
