-- Krafft — Phase 17 (part 3 of 5): exercise library expansion + hypertrophy guidance.
-- Run this after part 2. See part 1 for the full explanation.

insert into exercises (name, muscle_group, body_region, secondary_regions, equipment, cue_setup, cue_execution, cue_mistake, cue_bracing, hypertrophy_rep_range, hypertrophy_rest_interval, hypertrophy_tempo, hypertrophy_mind_muscle_cue) values
('Shrug', 'Pull', 'back', '{forearms}', 'Barbell',
  'Stand holding a bar or dumbbells at your sides, arms straight.',
  'Elevate your shoulders straight up toward your ears, pause briefly, then lower under control.',
  'Rolling the shoulders in a circular motion instead of a straight up-and-down path.',
  'Keep your arms straight and core braced — the movement should come entirely from the shoulders.',
  '10–15 reps', '60–90 sec', '1-1-2 tempo — pause at the top',
  'Try to touch your shoulders to your ears, holding the squeeze for a full second.'),
('Back Squat', 'Legs', 'quads', '{glutes,hamstrings}', 'Barbell',
  'Bar on your upper traps (high bar) or rear delts (low bar), feet roughly shoulder width.',
  'Break at the hips and knees together, descending until your hip crease is at or below knee level, then drive back up.',
  'Letting the knees cave inward on the way up, especially on a heavy last rep — it''s a common sign of fatigue or weak hips.',
  'Take a big breath and brace your abs hard before descending — hold that brace through the bottom of the rep.',
  '6–12 reps', '2–3 min', 'controlled 2-3 sec down, drive up with intent',
  'Think about spreading the floor apart with your feet as you stand up.'),
('Front Squat', 'Legs', 'quads', '{abs,glutes}', 'Barbell',
  'Bar racked across your front delts with elbows high, grip can be clean-style or crossed-arm.',
  'Squat down keeping your torso more upright than a back squat, then drive up through your heels/mid-foot.',
  'Letting the elbows drop lowers the bar off your shoulders and pitches your torso forward, losing the position.',
  'Brace your abs hard — an upright torso here depends more on core strength than on the back squat.',
  '6–10 reps', '2–3 min', 'controlled down, no bounce at the bottom',
  'Keep your elbows up and chest tall — imagine balancing a cup of water on your chest.'),
('Goblet Squat', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Hold a dumbbell or kettlebell vertically against your chest, feet shoulder width.',
  'Squat down between your knees until your thighs are at least parallel, then drive back up.',
  'Letting the weight pull your torso forward and rounding your upper back.',
  'Keep the weight held tight against your chest and your torso upright throughout.',
  '10–15 reps', '90 sec', '2-1-2 tempo',
  'Use your elbows to gently push your knees out as you descend.'),
('Leg Press', 'Legs', 'quads', '{glutes,hamstrings}', 'Machine',
  'Feet shoulder width on the platform, lower back flat against the pad.',
  'Lower the platform until your knees reach roughly 90°, then press back up without locking your knees hard at the top.',
  'Letting your lower back round off the pad as the weight gets heavy — usually a sign the range of motion is too deep for the load.',
  'Keep your core braced and lower back pinned to the pad throughout the set.',
  '10–15 reps', '90 sec–2 min', '2-1-2 tempo',
  'Focus on pushing through your whole foot, not just your toes.'),
('Bulgarian Split Squat', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Rear foot elevated on a bench, front foot far enough forward that your front shin stays close to vertical.',
  'Lower straight down until your back knee is near the floor, then drive up through your front foot.',
  'Placing the front foot too close to the bench forces the front knee too far forward and shifts the emphasis away from the glutes/hamstrings.',
  'Keep your torso tall and core tight — this is a balance-heavy movement, and a loose core makes it worse.',
  '8–12 reps per leg', '90 sec', '2-1-2 tempo',
  'Feel the stretch in your front-leg glute at the bottom before driving up.'),
('Walking Lunge', 'Legs', 'quads', '{glutes,hamstrings}', 'Dumbbell',
  'Stand tall holding dumbbells at your sides or a bar on your back.',
  'Step forward into a lunge, lowering your back knee toward the floor, then drive through your front foot to step into the next rep.',
  'Taking too short a step turns it into a knee-dominant exercise and adds unnecessary knee stress.',
  'Keep your torso upright and core braced — leaning forward shifts the work away from your legs and onto your lower back.',
  '10–15 reps per leg', '90 sec', 'controlled 2 sec descent per step',
  'Push the ground away from you with your front foot rather than pushing off your back foot.'),
('Reverse Lunge', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Stand tall holding dumbbells at your sides or a bar on your back.',
  'Step backward into a lunge, lowering your back knee toward the floor, then drive through your front foot to return to standing.',
  'Letting the front knee cave inward as you drive back up.',
  'Keep your torso upright and core braced throughout the step.',
  '10–15 reps per leg', '90 sec', '2-1-2 tempo',
  'Think about driving through your front heel to stand back up, not pushing off your back foot.'),
('Leg Extension', 'Legs', 'quads', '{}', 'Machine',
  'Sit with the pad resting just above your ankles, back against the seat.',
  'Extend your knees until your legs are straight, then lower back under control.',
  'Using momentum to kick the weight up at the top instead of a controlled extension through the full range.',
  'Keep your back against the pad and grip the seat handles to keep your upper body still.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Squeeze and hold at the top for a full second before lowering.'),
('Hip Thrust', 'Legs', 'glutes', '{hamstrings}', 'Barbell',
  'Upper back braced against a bench, bar across your hips, feet flat roughly shoulder width.',
  'Drive your hips up until your torso is roughly in line with your thighs, squeezing your glutes hard at the top.',
  'Overextending the lower back at the top to gain a few extra inches instead of stopping at a straight hip-to-shoulder line.',
  'Tuck your chin slightly and brace your abs at the top of each rep to avoid an exaggerated lower-back arch.',
  '8–15 reps', '90 sec–2 min', '1-2-1 tempo — pause and squeeze at the top',
  'Squeeze your glutes as hard as you can at the top, holding for a full second.'),
('Step-Up', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Stand facing a box or bench roughly knee height, dumbbells at your sides.',
  'Step up onto the box leading with one foot, driving through that leg to stand fully on top, then step back down under control.',
  'Pushing off the bottom leg to help you up instead of driving through the top leg.',
  'Keep your torso upright and place your whole foot on the box, not just your toes.',
  '10–15 reps per leg', '90 sec', 'controlled 2 sec down',
  'Focus all the driving effort through the leg that''s on the box.'),
('Stiff-Leg Deadlift', 'Legs', 'hamstrings', '{glutes,back}', 'Barbell',
  'Similar to a Romanian deadlift but with straighter (though not locked) knees, bar at hip height.',
  'Lower the bar along your legs by hinging at the hips until you feel a deep hamstring stretch, then drive your hips forward to stand.',
  'Locking the knees completely, which can strain the lower back and reduce hamstring involvement.',
  'Keep a flat back and braced core throughout — the range of motion is often shorter than an RDL since the legs stay straighter.',
  '8–12 reps', '90 sec–2 min', '3-1-1 tempo',
  'Focus on the stretch in your hamstrings as the primary signal, not how low the bar goes.'),
('Leg Curl', 'Legs', 'hamstrings', '{}', 'Machine',
  'Lie face down (or seated, depending on the machine) with the pad positioned just above your heels.',
  'Curl your heels toward your glutes, then lower back under control without letting the weight stack slam.',
  'Using a big hip lift to help the weight up instead of isolating the hamstrings — keep your hips pinned down.',
  'Keep your hips pressed into the pad/bench throughout the movement.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Curl your heels toward your glutes and squeeze hard at the top.'),
('Good Morning', 'Legs', 'hamstrings', '{glutes,back}', 'Barbell',
  'Bar on your upper back like a squat, feet shoulder width, soft bend in the knees.',
  'Hinge forward at the hips, keeping your back flat, until your torso is near parallel to the floor, then drive your hips forward to stand.',
  'Rounding the lower back as you hinge forward instead of keeping it flat and neutral.',
  'Brace your core hard before descending — this is one of the least forgiving lifts for a loose back.',
  '8–12 reps (start light — this movement has a steep learning curve)', '90 sec–2 min', 'controlled 2-3 sec hinge down',
  'Feel your hamstrings load up as you hinge, treating your hips as the hinge point, not your spine.'),
('Nordic Curl', 'Legs', 'hamstrings', '{}', 'Bodyweight',
  'Kneel with your ankles secured (partner holding them or under a pad), torso upright.',
  'Lower your torso toward the floor as slowly as possible by resisting with your hamstrings, catching yourself with your hands at the bottom, then use your hamstrings and hands to return.',
  'Letting the hips pike or bend forward instead of keeping a straight line from knees to head.',
  'Brace your core and glutes to keep your body in one straight line as you lower.',
  '3–8 reps (an advanced, eccentric-only movement for most lifters)', '90 sec–2 min', 'as slow as possible on the way down',
  'Fight the fall the entire way down — the slower you resist, the more it''s working.');
