-- Krafft — Phase 13: exercise database (cue cards, muscle map, split
-- builder, glossary all read from this one table).
-- Run this once in the Supabase SQL Editor against the existing live
-- database. Fresh installs get it automatically from reset-schema.sql
-- instead.
--
-- Global reference data, not user-scoped — every account reads the same
-- rows, so this is select-only via RLS with no insert/update/delete policy;
-- content is seeded by this migration, not user-editable. `muscle_group`
-- reuses the app's existing MUSCLE_GROUPS taxonomy (Legs/Push/Pull/Core/
-- Full Body/Other) and `body_region` the existing BODY_REGIONS list (see
-- index.html), so a lift row's own muscle_group/body_region can default
-- from here instead of the small hardcoded DEFAULT_MUSCLE_GROUP/
-- DEFAULT_BODY_REGION maps. `secondary_regions` is body regions, not
-- muscle groups — "Push" is too broad to be useful as a secondary tag,
-- but "triceps, shoulders" tells you something. Cues are static/pre-
-- written, not AI-generated, same spirit as the Layer 1 tips library.

create table exercises (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  muscle_group text not null,
  body_region text,
  secondary_regions text[] not null default '{}',
  equipment text not null,
  cue_setup text not null,
  cue_execution text not null,
  cue_mistake text not null,
  cue_bracing text not null,
  created_at timestamptz not null default now()
);

alter table exercises enable row level security;

create policy "exercises_select_all" on exercises for select using (true);

insert into exercises (name, muscle_group, body_region, secondary_regions, equipment, cue_setup, cue_execution, cue_mistake, cue_bracing) values
('Bench Press', 'Push', 'chest', '{triceps,shoulders}', 'Barbell',
  'Set up with eyes under the bar, feet flat and driving into the floor, shoulder blades pulled back and down.',
  'Lower the bar to your lower chest under control, then press up and slightly back toward your face.',
  'Flaring the elbows straight out to the sides instead of tucking them ~45° — it stresses the shoulder more and gives you less pressing power.',
  'Take a breath into your belly before unracking, and hold it through the hardest part of each rep.'),
('Incline Bench Press', 'Push', 'chest', '{shoulders,triceps}', 'Barbell',
  'Set the bench to a 30–45° incline — steeper shifts the work to shoulders, flatter shifts it back to chest.',
  'Lower the bar to your upper chest, just below the collarbone, then press up and slightly back.',
  'Setting the incline too steep turns this into an overhead press with extra shoulder strain instead of an upper-chest exercise.',
  'Keep your feet planted and glutes on the bench — don''t let your lower back arch off the pad to chase more range.'),
('Overhead Press', 'Push', 'shoulders', '{triceps,abs}', 'Barbell',
  'Grip just outside shoulder width, bar resting on your front delts, elbows slightly in front of the bar.',
  'Press straight up, moving your head back slightly to let the bar pass, then push your head through at the top.',
  'Leaning back excessively to help the bar clear your face turns this into an incline press and stresses the lower back.',
  'Squeeze your glutes and brace your abs like you''re about to be punched in the stomach — a loose torso leaks power.'),
('Dumbbell Shoulder Press', 'Push', 'shoulders', '{triceps}', 'Dumbbell',
  'Sit or stand with dumbbells at shoulder height, palms facing forward or slightly angled in.',
  'Press the dumbbells up and slightly together without locking your elbows aggressively at the top.',
  'Letting the dumbbells drift too far forward turns the shoulders into the limiting factor before the set is actually over.',
  'Keep your ribs down and core tight — an arched lower back is usually the first thing to give out here.'),
('Push-Up', 'Push', 'chest', '{triceps,abs}', 'Bodyweight',
  'Hands slightly wider than shoulders, body in a straight line from head to heels.',
  'Lower your chest to just above the floor with elbows at roughly 45°, then press back up.',
  'Letting the hips sag or pike up breaks the straight-line position and shifts load away from the chest.',
  'Brace your abs and squeeze your glutes throughout — treat it like a moving plank, not just an arm exercise.'),
('Dip', 'Push', 'chest', '{triceps,shoulders}', 'Bodyweight',
  'Grip the bars with arms straight, shoulders down and away from your ears.',
  'Lower until your shoulders are about level with your elbows, then press back to the top.',
  'Going too deep too soon puts a lot of stress on the front of the shoulder before you''ve built the mobility for it.',
  'Lean your torso forward slightly and keep your core tight to bias the chest and protect the shoulders.'),
('Close-Grip Bench Press', 'Push', 'triceps', '{chest}', 'Barbell',
  'Grip just inside shoulder width, elbows tucked close to your sides.',
  'Lower the bar to your lower chest keeping elbows tracking straight back, then press up.',
  'Gripping too narrow (hands touching) puts unnecessary strain on the wrists without adding tricep benefit.',
  'Same full-body brace as a regular bench — feet driving down, upper back tight against the bench.'),
('Tricep Pushdown', 'Push', 'triceps', '{}', 'Cable',
  'Grip the bar or rope with elbows pinned to your sides, standing tall.',
  'Extend your forearms down until your arms are straight, then control the weight back up.',
  'Letting the elbows drift forward or flare out turns this into a shoulder/chest movement instead of isolating the triceps.',
  'Keep your torso still — using body momentum to help the weight down is the most common way to cheat this exercise.'),
('Lateral Raise', 'Push', 'shoulders', '{}', 'Dumbbell',
  'Stand with a slight forward lean, dumbbells at your sides with a soft bend in the elbows.',
  'Raise the dumbbells out to the sides until roughly shoulder height, leading with your elbows.',
  'Using momentum to swing the weight up trains your traps more than your side delts — the target muscle.',
  'Keep your core braced so you''re not using a body swing to substitute for shoulder strength.'),
('Deadlift', 'Pull', 'back', '{hamstrings,glutes}', 'Barbell',
  'Bar over mid-foot, shins close to the bar, grip just outside your knees, hips higher than the knees, chest up.',
  'Drive through the floor with your legs while keeping the bar close to your body until you''re standing tall.',
  'Letting the bar drift away from your shins/thighs turns the lift into a lower-back grinder instead of a leg-and-hip drive.',
  'Take a big breath and brace your entire torso like a weightlifting belt before the bar leaves the floor.'),
('Barbell Row', 'Pull', 'back', '{biceps,forearms}', 'Barbell',
  'Hinge at the hips to roughly a 45° torso angle, grip just outside shoulder width.',
  'Pull the bar to your lower ribcage, squeezing your shoulder blades together at the top.',
  'Standing up more with each rep (turning it into a mini deadlift) as fatigue sets in instead of holding the hinge.',
  'Keep your core braced and back flat throughout — this is a hip-hinge position, not just an arm pull.'),
('Pull-Up', 'Pull', 'back', '{biceps,forearms}', 'Bodyweight',
  'Grip just outside shoulder width, palms facing away, hang with arms fully extended.',
  'Pull your chin over the bar leading with your chest, then lower back to a full hang under control.',
  'Only doing the top half of the rep (partial range) trains less muscle and builds strength you can''t actually use.',
  'Keep a slight hollow-body brace so you''re not using an uncontrolled kip or swing to gain momentum.'),
('Chin-Up', 'Pull', 'back', '{biceps}', 'Bodyweight',
  'Grip shoulder width, palms facing you, hang with arms fully extended.',
  'Pull yourself up until your chin clears the bar, then lower back down under control.',
  'Turning it into a chest-up crunch instead of a straight vertical pull reduces the actual back/bicep work.',
  'Keep your ribs down and core tight to avoid an excessive arch through your lower back.'),
('Lat Pulldown', 'Pull', 'back', '{biceps}', 'Cable',
  'Grip slightly wider than shoulder width, sit tall with thighs secured under the pad.',
  'Pull the bar to your upper chest, driving your elbows down and back, then control it back up.',
  'Leaning back excessively and using body weight instead of your back muscles to move the bar.',
  'Keep your chest up and core braced — a small, controlled lean is fine, but a big swing is momentum, not strength.'),
('Seated Cable Row', 'Pull', 'back', '{biceps,forearms}', 'Cable',
  'Sit with knees slightly bent, back tall, grip the handle with arms extended.',
  'Pull the handle to your torso, squeezing your shoulder blades together, then extend back out under control.',
  'Rounding your lower back to add a few extra inches of pull range instead of keeping a tall, stable torso.',
  'Keep your torso upright and braced throughout — the movement should come from your arms and shoulder blades, not your spine rocking.'),
('Face Pull', 'Pull', 'shoulders', '{back}', 'Cable',
  'Set the cable at roughly face height, grip the rope with palms facing in.',
  'Pull the rope toward your face, flaring your elbows out wide and rotating your hands back.',
  'Pulling with too much weight and turning it into a row instead of a high-elbow rear-delt/rotator cuff movement.',
  'Keep your upper back tight and shoulders down away from your ears throughout the pull.'),
('Barbell Curl', 'Pull', 'biceps', '{forearms}', 'Barbell',
  'Stand tall, grip shoulder width, elbows pinned to your sides.',
  'Curl the bar up by bending your elbows, keeping your upper arms still, then lower under control.',
  'Swinging the hips and leaning back to heave the weight up — it takes the tension off the biceps entirely.',
  'Keep your core tight and elbows locked in place so the only thing moving is your forearms.'),
('Dumbbell Curl', 'Pull', 'biceps', '{forearms}', 'Dumbbell',
  'Stand or sit with dumbbells at your sides, palms facing forward or neutral.',
  'Curl one or both dumbbells up, optionally rotating to a full supination at the top, then lower under control.',
  'Letting the elbow drift forward as the weight gets heavy, which lets the front delt take over the movement.',
  'Keep your upper arm pinned against your torso throughout the rep.'),
('Back Squat', 'Legs', 'quads', '{glutes,hamstrings}', 'Barbell',
  'Bar on your upper traps (high bar) or rear delts (low bar), feet roughly shoulder width.',
  'Break at the hips and knees together, descending until your hip crease is at or below knee level, then drive back up.',
  'Letting the knees cave inward on the way up, especially on a heavy last rep — it''s a common sign of fatigue or weak hips.',
  'Take a big breath and brace your abs hard before descending — hold that brace through the bottom of the rep.'),
('Front Squat', 'Legs', 'quads', '{abs,glutes}', 'Barbell',
  'Bar racked across your front delts with elbows high, grip can be clean-style or crossed-arm.',
  'Squat down keeping your torso more upright than a back squat, then drive up through your heels/mid-foot.',
  'Letting the elbows drop lowers the bar off your shoulders and pitches your torso forward, losing the position.',
  'Brace your abs hard — an upright torso here depends more on core strength than on the back squat.'),
('Romanian Deadlift', 'Legs', 'hamstrings', '{glutes,back}', 'Barbell',
  'Start standing with the bar at hip height, soft bend in the knees that stays fixed through the rep.',
  'Push your hips back, lowering the bar along your legs until you feel a stretch in your hamstrings, then drive your hips forward to stand.',
  'Bending the knees more as the bar lowers turns it into a squat and takes tension off the hamstrings — the actual target.',
  'Keep your back flat and core braced — the movement is a hip hinge, not a spinal round.'),
('Leg Press', 'Legs', 'quads', '{glutes,hamstrings}', 'Machine',
  'Feet shoulder width on the platform, lower back flat against the pad.',
  'Lower the platform until your knees reach roughly 90°, then press back up without locking your knees hard at the top.',
  'Letting your lower back round off the pad as the weight gets heavy — usually a sign the range of motion is too deep for the load.',
  'Keep your core braced and lower back pinned to the pad throughout the set.'),
('Walking Lunge', 'Legs', 'quads', '{glutes,hamstrings}', 'Dumbbell',
  'Stand tall holding dumbbells at your sides or a bar on your back.',
  'Step forward into a lunge, lowering your back knee toward the floor, then drive through your front foot to step into the next rep.',
  'Taking too short a step turns it into a knee-dominant exercise and adds unnecessary knee stress.',
  'Keep your torso upright and core braced — leaning forward shifts the work away from your legs and onto your lower back.'),
('Bulgarian Split Squat', 'Legs', 'quads', '{glutes}', 'Dumbbell',
  'Rear foot elevated on a bench, front foot far enough forward that your front shin stays close to vertical.',
  'Lower straight down until your back knee is near the floor, then drive up through your front foot.',
  'Placing the front foot too close to the bench forces the front knee too far forward and shifts the emphasis away from the glutes/hamstrings.',
  'Keep your torso tall and core tight — this is a balance-heavy movement, and a loose core makes it worse.'),
('Leg Curl', 'Legs', 'hamstrings', '{}', 'Machine',
  'Lie face down (or seated, depending on the machine) with the pad positioned just above your heels.',
  'Curl your heels toward your glutes, then lower back under control without letting the weight stack slam.',
  'Using a big hip lift to help the weight up instead of isolating the hamstrings — keep your hips pinned down.',
  'Keep your hips pressed into the pad/bench throughout the movement.'),
('Leg Extension', 'Legs', 'quads', '{}', 'Machine',
  'Sit with the pad resting just above your ankles, back against the seat.',
  'Extend your knees until your legs are straight, then lower back under control.',
  'Using momentum to kick the weight up at the top instead of a controlled extension through the full range.',
  'Keep your back against the pad and grip the seat handles to keep your upper body still.'),
('Hip Thrust', 'Legs', 'glutes', '{hamstrings}', 'Barbell',
  'Upper back braced against a bench, bar across your hips, feet flat roughly shoulder width.',
  'Drive your hips up until your torso is roughly in line with your thighs, squeezing your glutes hard at the top.',
  'Overextending the lower back at the top to gain a few extra inches instead of stopping at a straight hip-to-shoulder line.',
  'Tuck your chin slightly and brace your abs at the top of each rep to avoid an exaggerated lower-back arch.'),
('Calf Raise', 'Legs', 'calves', '{}', 'Machine',
  'Stand on a raised edge or platform with your heels hanging off, balls of your feet planted.',
  'Rise up onto your toes as high as possible, pause briefly, then lower your heels below the platform for a full stretch.',
  'Using short, bouncy reps instead of a full stretch at the bottom and a full contraction at the top — most of the benefit is in that full range.',
  'Keep your knees roughly straight (soft, not locked) so the calves — not the knees — are doing the work.'),
('Plank', 'Core', 'abs', '{}', 'Bodyweight',
  'Forearms on the floor under your shoulders, body in a straight line from head to heels.',
  'Hold the position, breathing normally, keeping your hips level — neither sagging nor piking up.',
  'Letting the hips sag toward the floor as fatigue sets in, which shifts the load onto the lower back instead of the abs.',
  'Actively squeeze your abs and glutes throughout — a plank is an active brace, not just a static hold.'),
('Hanging Leg Raise', 'Core', 'abs', '{forearms}', 'Bodyweight',
  'Hang from a bar with a full grip, legs extended or knees bent depending on your level.',
  'Curl your hips up and raise your legs (or knees) toward your chest, then lower under control without swinging.',
  'Using momentum from a swing to fling the legs up instead of a controlled hip curl driven by the abs.',
  'Keep your ribs pulled down toward your pelvis throughout — an arched lower back means the hip flexors are taking over from the abs.'),
('Ab Wheel Rollout', 'Core', 'abs', '{shoulders}', 'Bodyweight',
  'Kneel on a pad, hands gripping the wheel directly under your shoulders.',
  'Roll forward as far as you can control, keeping your core braced, then pull back to the start using your abs, not your arms.',
  'Letting the lower back sag as you roll out — that''s usually the sign you''ve gone further than your current core strength supports.',
  'Brace your abs hard through the entire rollout — imagine trying to keep a flat line from your shoulders to your knees.'),
('Power Clean', 'Full Body', null, '{back,quads,shoulders}', 'Barbell',
  'Bar over mid-foot, same starting position as a deadlift, grip just outside shoulder width.',
  'Pull the bar explosively from the floor, extending through the hips as it passes your thighs, then drop under it to catch it on your front delts.',
  'Muscling the bar up with your arms early instead of using an explosive hip extension — the arms should stay relatively passive until the very end of the pull.',
  'Brace hard off the floor just like a deadlift, then reset that brace quickly to catch the bar in the front-rack position.');
