-- Krafft — Phase 17 (part 1 of 5): exercise library expansion + hypertrophy guidance.
-- Split into smaller files purely to make copy/paste into the Supabase SQL
-- Editor more reliable on long pastes (a partial paste of the original single
-- ~580-line file was silently truncating for some users, producing a syntax
-- error deep in the VALUES list). Run all parts in order, part 1 through part
-- 5. Each part is a complete, independently valid SQL statement.

alter table exercises add column if not exists hypertrophy_rep_range text;
alter table exercises add column if not exists hypertrophy_rest_interval text;
alter table exercises add column if not exists hypertrophy_tempo text;
alter table exercises add column if not exists hypertrophy_mind_muscle_cue text;

truncate table exercises;

insert into exercises (name, muscle_group, body_region, secondary_regions, equipment, cue_setup, cue_execution, cue_mistake, cue_bracing, hypertrophy_rep_range, hypertrophy_rest_interval, hypertrophy_tempo, hypertrophy_mind_muscle_cue) values
('Bench Press', 'Push', 'chest', '{triceps,shoulders}', 'Barbell',
  'Set up with eyes under the bar, feet flat and driving into the floor, shoulder blades pulled back and down.',
  'Lower the bar to your lower chest under control, then press up and slightly back toward your face.',
  'Flaring the elbows straight out to the sides instead of tucking them ~45° — it stresses the shoulder more and gives you less pressing power.',
  'Take a breath into your belly before unracking, and hold it through the hardest part of each rep.',
  '6–12 reps', '2–3 min', '2-1-1 tempo — lower for 2 seconds, brief pause on the chest, drive up',
  'Think about pushing yourself away from the bar, not just pushing the bar away from you.'),
('Incline Bench Press', 'Push', 'chest', '{shoulders,triceps}', 'Barbell',
  'Set the bench to a 30–45° incline — steeper shifts the work to shoulders, flatter shifts it back to chest.',
  'Lower the bar to your upper chest, just below the collarbone, then press up and slightly back.',
  'Setting the incline too steep turns this into an overhead press with extra shoulder strain instead of an upper-chest exercise.',
  'Keep your feet planted and glutes on the bench — don''t let your lower back arch off the pad to chase more range.',
  '8–12 reps', '2 min', '2-1-1 tempo',
  'Focus on driving through your upper chest, not just your shoulders.'),
('Decline Bench Press', 'Push', 'chest', '{triceps}', 'Barbell',
  'Secure your feet in the decline bench''s foot pads, lie back with eyes under the bar.',
  'Lower the bar to your lower chest, then press up and slightly back.',
  'Bouncing the bar off the chest to use momentum instead of controlling the full range.',
  'Keep your shoulder blades pulled back and down against the bench throughout.',
  '8–12 reps', '2 min', '2-1-1 tempo',
  'Focus on squeezing the lower chest at the top of the press.'),
('Dumbbell Bench Press', 'Push', 'chest', '{triceps,shoulders}', 'Dumbbell',
  'Lie on a flat bench with a dumbbell in each hand at chest level, elbows bent.',
  'Press the dumbbells up until your arms are extended, then lower under control back to chest level.',
  'Letting the dumbbells drift too far apart or together at the top, losing tension on the chest.',
  'Keep your feet flat on the floor and glutes on the bench for a stable base to press from.',
  '8–12 reps', '90 sec–2 min', '2-1-2 tempo',
  'Squeeze your chest together at the top like you''re hugging a barrel.'),
('Incline Dumbbell Press', 'Push', 'chest', '{shoulders,triceps}', 'Dumbbell',
  'Set the bench to a 30–45° incline, dumbbells at shoulder height.',
  'Press the dumbbells up and slightly in, then lower under control.',
  'Setting the incline too steep, which shifts the work to the shoulders instead of the upper chest.',
  'Keep your lower back flat against the bench, not arched off it.',
  '8–12 reps', '90 sec', '2-1-2 tempo',
  'Picture pressing up and slightly toward the ceiling above your opposite eye.'),
('Dumbbell Fly', 'Push', 'chest', '{shoulders}', 'Dumbbell',
  'Lie on a flat bench with dumbbells held above your chest, a slight bend in the elbows.',
  'Lower the dumbbells out to the sides in a wide arc until you feel a stretch in the chest, then bring them back together.',
  'Bending the elbows more as the weight gets heavy, which turns the fly into a press.',
  'Keep that slight elbow bend fixed throughout — don''t let it change between reps.',
  '10–15 reps', '60–90 sec', '3-1-1 tempo — slow, controlled stretch down',
  'Imagine wrapping your arms around a large barrel, feeling the stretch across your chest.'),
('Cable Fly', 'Push', 'chest', '{shoulders}', 'Cable',
  'Set both pulleys to chest height (or adjust for upper/lower chest emphasis), grip the handles with a slight forward lean.',
  'Bring your hands together in front of your chest in a hugging motion, then return under control.',
  'Using too much weight and turning the movement into a press by bending the elbows more.',
  'Keep a stable, slight forward lean and don''t let your torso rock to help move the weight.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Focus on squeezing your chest together at the peak, holding briefly before releasing.'),
('Pec Deck', 'Push', 'chest', '{shoulders}', 'Machine',
  'Sit with your back flat against the pad, forearms or hands on the arm pads at chest height.',
  'Bring the pads together in front of your chest, then let them return under control.',
  'Letting the weight stack slam down between reps instead of controlling the stretch.',
  'Keep your back pressed into the pad throughout — don''t let it round forward as you squeeze.',
  '12–15 reps', '60 sec', '2-1-2 tempo',
  'Squeeze and hold for a full second at the point your hands are closest together.'),
('Push-Up', 'Push', 'chest', '{triceps,abs}', 'Bodyweight',
  'Hands slightly wider than shoulders, body in a straight line from head to heels.',
  'Lower your chest to just above the floor with elbows at roughly 45°, then press back up.',
  'Letting the hips sag or pike up breaks the straight-line position and shifts load away from the chest.',
  'Brace your abs and squeeze your glutes throughout — treat it like a moving plank, not just an arm exercise.',
  '10–20 reps (add weight or elevate feet once bodyweight gets easy)', '60–90 sec', '2-1-1 tempo',
  'Think about pushing the floor away from you rather than just straightening your arms.'),
('Dip (Chest-Focused)', 'Push', 'chest', '{triceps,shoulders}', 'Bodyweight',
  'Grip the bars with arms straight, lean your torso forward to bias the chest over the triceps.',
  'Lower until you feel a stretch in the chest, then press back up, keeping the forward lean.',
  'Staying too upright, which shifts the emphasis to triceps instead of chest.',
  'Keep your core braced and shoulders down — a forward lean should come from the hips, not a rounded back.',
  '8–15 reps (add weight once bodyweight gets easy)', '90 sec–2 min', '2-1-1 tempo',
  'Lead with your chest on the way down, like you''re diving forward into the stretch.'),
('Deadlift', 'Pull', 'back', '{hamstrings,glutes}', 'Barbell',
  'Bar over mid-foot, shins close to the bar, grip just outside your knees, hips higher than the knees, chest up.',
  'Drive through the floor with your legs while keeping the bar close to your body until you''re standing tall.',
  'Letting the bar drift away from your shins/thighs turns the lift into a lower-back grinder instead of a leg-and-hip drive.',
  'Take a big breath and brace your entire torso like a weightlifting belt before the bar leaves the floor.',
  '5–10 reps', '2–3 min', 'controlled down (2-3 sec), no bounce off the floor on the next rep',
  'Think about pushing the floor away with your legs first, then finishing tall with your hips.'),
('Romanian Deadlift', 'Legs', 'hamstrings', '{glutes,back}', 'Barbell',
  'Start standing with the bar at hip height, soft bend in the knees that stays fixed through the rep.',
  'Push your hips back, lowering the bar along your legs until you feel a stretch in your hamstrings, then drive your hips forward to stand.',
  'Bending the knees more as the bar lowers turns it into a squat and takes tension off the hamstrings — the actual target.',
  'Keep your back flat and core braced — the movement is a hip hinge, not a spinal round.',
  '8–12 reps', '90 sec–2 min', '3-1-1 tempo — slow lowering to really feel the stretch',
  'Focus on feeling a deep stretch in your hamstrings before you reverse the movement.'),
('Barbell Row', 'Pull', 'back', '{biceps,forearms}', 'Barbell',
  'Hinge at the hips to roughly a 45° torso angle, grip just outside shoulder width.',
  'Pull the bar to your lower ribcage, squeezing your shoulder blades together at the top.',
  'Standing up more with each rep (turning it into a mini deadlift) as fatigue sets in instead of holding the hinge.',
  'Keep your core braced and back flat throughout — this is a hip-hinge position, not just an arm pull.',
  '8–12 reps', '90 sec–2 min', '1-1-2 tempo — control the lowering more than the pull',
  'Pull with your elbows, not your hands — imagine driving your elbows toward the ceiling.'),
('Pendlay Row', 'Pull', 'back', '{biceps,forearms}', 'Barbell',
  'Bar on the floor, hinge over to a flat-back, near-horizontal torso position, grip just outside shoulder width.',
  'Pull the bar explosively off the floor to your lower chest/upper abs, then lower it back to a dead stop each rep.',
  'Using body English (a hip heave) to start the pull instead of pulling with the back.',
  'Keep your torso locked in that horizontal position throughout the set — it shouldn''t rise as you fatigue.',
  '6–10 reps', '90 sec–2 min', 'explosive up, controlled down, dead stop each rep',
  'Reset your brace fully between every rep — treat each one as its own lift.'),
('Dumbbell Row', 'Pull', 'back', '{biceps,forearms}', 'Dumbbell',
  'One knee and hand on a bench for support, other foot on the floor, dumbbell hanging in your free hand.',
  'Pull the dumbbell up to your hip, driving your elbow back, then lower under control.',
  'Rotating your torso to help heave the weight up instead of keeping it square.',
  'Keep your supporting arm locked and your back flat, not rounded, throughout the set.',
  '8–12 reps', '90 sec', '1-1-2 tempo',
  'Imagine trying to touch your elbow to the ceiling at the top of each rep.');
